#pragma once

#include <cstdint>

namespace chronon3d::effects {

// ── EffectType ──────────────────────────────────────────────────────────────
// Maps each concrete param struct to a compile-time tag for O(1) dispatch.
// Values are EXPLICITLY assigned to guarantee stability when new effects are
// inserted — never rely on auto-increment order.
//
// Values 1-12 are existing effects; 13-21 are reserved for future additions
// (Exposure, Levels, Curves, Fill, Noise, Offset, DirectionalBlur, RadialBlur,
// Stroke).

enum class EffectType : uint8_t {
    Unknown         = 0,

    // ── Core effects (existing) ──
    Blur            = 1,
    Tint            = 2,
    Brightness      = 3,
    Contrast        = 4,
    DropShadow      = 5,
    Glow            = 6,
    Bloom           = 7,
    Fake3DWave      = 8,
    Saturation      = 9,
    HueRotate       = 10,
    Invert          = 11,
    Vignette        = 12,

    // ── Future effects (reserved by A1, implemented by follow-up agents) ──
    Exposure        = 13,
    Levels          = 14,
    Curves          = 15,
    Fill            = 16,
    Noise           = 17,
    Offset          = 18,
    DirectionalBlur = 19,
    RadialBlur      = 20,
    Stroke          = 21,
};

// ── effect_type_for<T> primary template ─────────────────────────────────────
// Returns Unknown by default.  Specializations are generated by the X-macro
// catalog for each known effect parameter type.

template <typename T>
struct effect_type_for {
    static constexpr EffectType value = EffectType::Unknown;
};

} // namespace chronon3d::effects
