# General sources for chronon3d_core_tests.
set(CORE_TEST_SOURCES
    core/test_frame_context.cpp
    core/memory/test_huge_page_allocator.cpp
    core/math/test_math.cpp
    core/math/test_output_transform.cpp
    simd/test_simd_kernels.cpp
    simd/test_kernel_resolver_avx2_parity.cpp
    cache/test_lru_weight.cpp
    cache/test_lru_cache.cpp
    cache/test_framebuffer_pool.cpp
    cache/test_video_frame_cache.cpp
    cache/test_persistent_framebuffer_store.cpp
    cache/test_evict_lru_for.cpp
    core/test_sharded_telemetry_store.cpp
    core/test_render_counters.cpp
    core/test_cache_eval_dirty_counters.cpp
    core/math/test_camera_pose.cpp
    core/math/test_camera_2_5d_projection.cpp
    core/math/test_projector_2_5d.cpp
    core/math/test_2_5d_roadmap.cpp
    core/math/test_camera_projection_resolver.cpp
    core/math/test_camera_projection_geometry_safety.cpp
    core/math/test_clip_with_uv.cpp
    core/math/test_frustum_culling.cpp
    core/geometry/test_geometry.cpp
    text/test_text_placement_resolver.cpp
    core/animation/test_animation.cpp
    core/animation/test_interpolate.cpp
    core/animation/test_spring.cpp
    core/animation/test_animated_value.cpp
    core/animation/test_animated_value_expression.cpp
    core/animation/test_keyframes.cpp
    core/animation/test_keyframe_tracks.cpp
    core/animation/test_animated_transform.cpp
    core/animation/test_cubic_bezier.cpp
    core/animation/test_stagger.cpp
    core/animation/test_animation_curve.cpp
    core/animation/test_animation_track.cpp
    core/animation/test_wiggle.cpp
    core/animation/test_sample_time.cpp
    core/test_frame_rate_edge_cases.cpp
    core/animation/test_temporal_spatial_curve.cpp
    core/animation/path/test_catmull_rom_path.cpp
    core/animation/path/test_spatial_bezier_path.cpp
    core/animation/test_quaternion_track.cpp
    core/timeline/test_timeline.cpp
    core/timeline/test_timeline_builder.cpp
    core/timeline/test_code_first_composition.cpp
    core/timeline/test_sequence.cpp
    test_project.cpp
    core/timeline/test_timeline_resolver.cpp
    core/timeline/test_sequence_builder.cpp
    core/timeline/test_sequence_animation.cpp
    core/timeline/test_sequence_integration.cpp
    assets/test_svg_path_loader.cpp
    assets/test_render_preflight.cpp
    assets/test_asset_registry.cpp
    assets/test_asset_resolver.cpp
    assets/test_asset_manifest.cpp
    assets/test_asset_preflight_resolver.cpp
    core/math/test_color_space.cpp
    core/math/test_nan_guard.cpp
    core/test_system_metrics_parse.cpp
    core/test_execution_scope.cpp
    core/test_cpu_budget.cpp
    core/math/test_expression.cpp
    core/math/test_expression_extended.cpp
    test_text_preset_registry.cpp
    registry/test_text_preset_descriptor.cpp
    text/test_text_run_umbrella_contract.cpp
    text/test_text_run_multi_run_failure_policy.cpp
    ${CORE_BLEND2D_TESTS}
    media/test_media_placement.cpp
    core/test_result.cpp
    core/test_scene_hasher_camera.cpp
    render_graph/executor/test_cache_key_contract.cpp
    render_graph/executor/test_framebuffer_lifetime.cpp
    render_graph/executor/test_text_bbox_reconcile.cpp
    render_graph/executor/test_executor_levels_parallel.cpp
    render_graph/builder/test_graph_build_pass_order.cpp
    runtime/test_render_session_reset_and_isolation.cpp
    runtime/test_camera_session_keep_last_valid.cpp
    runtime/test_camera_session_cache_failed_no_commit.cpp
    runtime/test_render_runtime_isolation.cpp
    runtime/test_camera_session_cache_failed_no_commit_session_state.cpp
    ${CMAKE_SOURCE_DIR}/tools/test_software_renderer_boundary_consistency.cpp
)
