# Single ordered manifest of per-area test definition files.
set(CHRONON3D_TEST_DEFINITIONS
    mesh_disabled_gate.cmake
    backends_software_tests.cmake
    debug/CMakeLists.txt
    architecture_tests.cmake
    ocio_tests.cmake
    core_tests.cmake
    backend_registry_tests.cmake
    shader_abi_tests.cmake
    ipc_tests.cmake
    memory_tests.cmake
    c_abi_tests.cmake
    scene_tests.cmake
    cli_tests.cmake
    introspection_tests.cmake
    render_job_contract_tests.cmake
    optimizer_tests.cmake
    preflight_tests.cmake
    cache_tests.cmake
    compositor_tests.cmake
    benchmarks.cmake
    animation_tests.cmake
    renderer_tests.cmake
    io_tests.cmake
    parallelism_tests.cmake
    visual_tests.cmake
    graphics_tests.cmake
    gradient_visual_tests.cmake
    rounded_rect_visual_tests.cmake
    deterministic_tests.cmake
    text_production_v1_tests.cmake
    text_health_tests.cmake
    text_fallback_tests.cmake
    cache/parse_framebuffer_pool_clear_policy_tests.cmake
    diagnostic_overlay_tests.cmake
    precomp_focus_tests.cmake
    timeline_tests.cmake
    timeline_functional_v1_tests.cmake
    text_definition_tests.cmake
    safe_area_placement_tests.cmake
    text_rich_authoring_tests.cmake
    animation_helpers_tests.cmake
    text/text_clip_policy_tests.cmake
    text_layout_advanced_tests.cmake
    bench_corpus/CMakeLists.txt
    video_tests.cmake
    media_tests.cmake
    sdk_tests.cmake
    simd/simd_parity_blend_tests.cmake
    simd/cpu_isa_tests.cmake
    render_graph/compiler/fusion_pass_tests.cmake
    render_graph/compiler/template_program_tests.cmake
    render_graph/compiler/segment_execution_tests.cmake
    runtime/template_program_cache_tests.cmake
    runtime/gpu_layer_batch_tests.cmake
    runtime/gpu_command_plan_tests.cmake
    runtime/resource_state_tracker_tests.cmake
    runtime/compiled_resource_authority_tests.cmake
    runtime/async_encoder_sink_tests.cmake
    runtime/semantic_core_tests.cmake
    render_graph/pipeline/glow_fullframe_audit_tests.cmake
    sabotage_tests.cmake
    reference/capcut/CMakeLists.txt
    text/CMakeLists.txt
    assets/CMakeLists.txt
    ipc_schema_documents_tests.cmake
)
