# Single ordered manifest of per-area test definition files.
set(CHRONON3D_TEST_DEFINITIONS
    backends_software_tests.cmake
    debug/CMakeLists.txt
    core_tests.cmake
    shader_abi_tests.cmake
    ipc_tests.cmake
    scene_tests.cmake
    cli_tests.cmake
    render_runtime_tests.cmake
    benchmarks.cmake
    animation_timeline_tests.cmake
    renderer_tests.cmake
    text_domain_tests.cmake
    video_tests.cmake
    media_tests.cmake
    sdk_tests.cmake
    simd_tests.cmake
    assets/CMakeLists.txt
)
