# Single ordered manifest of per-area test definition files.
set(CHRONON3D_TEST_DEFINITIONS
    backends_software_tests.cmake
    debug/CMakeLists.txt
    core_tests.cmake
    scene_tests.cmake
    cli_tests.cmake
    introspection_tests.cmake
    render_job_contract_tests.cmake
    optimizer_tests.cmake
    preflight_tests.cmake
    cache_tests.cmake
    compositor_tests.cmake
    benchmarks.cmake
    authoring_tests.cmake
    animation_tests.cmake
    renderer_tests.cmake
    io_tests.cmake
    breathing_golden_tests.cmake
    visual_tests.cmake
    graphics_tests.cmake
    gradient_visual_tests.cmake
    rounded_rect_visual_tests.cmake
    deterministic_tests.cmake
    text_golden_tests.cmake
    text_production_v1_tests.cmake
    text_health_tests.cmake
    text_fallback_tests.cmake
    golden_matrix_subtitle_tests.cmake
    golden_matrix_emphasis_tests.cmake
    golden_matrix_cinematic_tests.cmake
    golden_matrix_reveal_tests.cmake
    cache/parse_framebuffer_pool_clear_policy_tests.cmake
    diagnostic_overlay_tests.cmake
    presets_golden_tests.cmake
    text_preset_visual_tests.cmake
    precomp_focus_tests.cmake
    timeline_tests.cmake
    timeline_functional_v1_tests.cmake
    text_definition_tests.cmake
    safe_area_placement_tests.cmake
    text_builder_ergonomics_tests.cmake
    text_rich_authoring_tests.cmake
    subtitle_productive_tests.cmake
    animation_helpers_tests.cmake
    text_simplicity_adapters_tests.cmake
    text/text_clip_policy_tests.cmake
    text_presets_stability_tests.cmake
    text_canvas_aware_presets_tests.cmake
    text_layout_advanced_tests.cmake
    content_tests.cmake
    showcase/CMakeLists.txt
    bench_corpus/CMakeLists.txt
    video_tests.cmake
    media_tests.cmake
    sdk_tests.cmake
    simd/simd_parity_blend_tests.cmake
    render_graph/compiler/fusion_pass_tests.cmake
    render_graph/pipeline/glow_fullframe_audit_tests.cmake
    sabotage_tests.cmake
)
