#include <doctest/doctest.h>
#include <chronon3d/renderer/software/software_renderer.hpp>
#include <chronon3d/renderer/assets/image_renderer.hpp>
#include <chronon3d/scene/scene_builder.hpp>
#include <filesystem>

using namespace chronon3d;

TEST_CASE("Image renderer fails safely on missing image") {
    Framebuffer fb(100, 100);
    fb.clear(Color{0, 0, 0, 1});

    ImageShape img;
    img.path = "assets/images/does_not_exist.png";
    img.size = {50, 50};
    img.opacity = 1.0f;

    ImageRenderer renderer;
    RenderState state{Mat4(1.0f), 1.0f};

    CHECK_FALSE(renderer.draw_image(img, state, fb));
}

TEST_CASE("Image renderer produces non-empty pixels") {
    const std::string path = "assets/images/checker.png";
    
    // We assume checker.png has been generated by CheckerGen or exists
    if (!std::filesystem::exists(path)) {
        // Skip test if asset is missing (e.g. first run)
        return;
    }

    Framebuffer fb(200, 200);
    fb.clear(Color{0, 0, 0, 1});

    ImageShape img;
    img.path = path;
    img.size = {100, 100};
    img.opacity = 1.0f;

    Transform tr;
    tr.position = {100, 100, 0};
    tr.anchor = {50, 50, 0};

    RenderState root{Mat4(1.0f), 1.0f};
    RenderState state = combine(root, tr);

    ImageRenderer renderer;
    REQUIRE(renderer.draw_image(img, state, fb));

    bool found = false;

    for (int y = 0; y < fb.height(); ++y) {
        for (int x = 0; x < fb.width(); ++x) {
            auto p = fb.get_pixel(x, y);
            if (p.r > 0.01f || p.g > 0.01f || p.b > 0.01f) {
                found = true;
                break;
            }
        }
        if (found) break;
    }

    CHECK(found);
}

TEST_CASE("Image opacity affects output") {
    const std::string path = "assets/images/checker.png";
    if (!std::filesystem::exists(path)) return;

    auto render_with_opacity = [&](f32 opacity) {
        Framebuffer fb(200, 200);
        fb.clear(Color{0, 0, 0, 1});

        ImageShape img;
        img.path = path;
        img.size = {100, 100};
        img.opacity = opacity;

        Transform tr;
        tr.position = {100, 100, 0};
        tr.anchor = {50, 50, 0};

        RenderState state = combine(RenderState{Mat4(1.0f), 1.0f}, tr);

        ImageRenderer renderer;
        REQUIRE(renderer.draw_image(img, state, fb));

        f32 sum = 0.0f;
        for (i32 y = 0; y < fb.height(); ++y) {
            for (i32 x = 0; x < fb.width(); ++x) {
                auto p = fb.get_pixel(x, y);
                sum += p.r + p.g + p.b;
            }
        }

        return sum;
    };

    f32 full = render_with_opacity(1.0f);
    f32 half = render_with_opacity(0.5f);

    CHECK(full > half);
    CHECK(half > 0.0f);
}

TEST_CASE("Image inside layer follows layer position") {
    const std::string path = "assets/images/checker.png";
    if (!std::filesystem::exists(path)) return;

    Composition comp = composition({
        .name = "ImageLayerPositionTest",
        .width = 300,
        .height = 300,
        .duration = 1
    }, [&](const FrameContext& ctx) {
        SceneBuilder s(ctx);

        s.layer("image-layer", [&](LayerBuilder& l) {
            l.position({150, 150, 0});
            l.image("img", {
                .path = path,
                .size = {80, 80},
                .pos = {0, 0, 0},
                .opacity = 1.0f
            });
        });

        return s.build();
    });

    SoftwareRenderer renderer;
    auto fb = renderer.render_frame(comp, 0);

    auto p = fb->get_pixel(150, 150);

    CHECK((p.r > 0.01f || p.g > 0.01f || p.b > 0.01f));
}
