#!/bin/bash
# Chronon3D Telemetry Dashboard — dev helper
#
# Starts the Flask backend and Vite frontend for local development.
# Usage:
#   ./start_telemetry.sh           # start both services
#   ./start_telemetry.sh --kill    # stop both services
#
# Configuration (env vars):
#   CHRONON3D_DASHBOARD_PASSWORD   Password for dashboard access (default: autogenerated)
#   VITE_BACKEND_PORT              Backend port for Vite proxy      (default: 5005)
#   BACKEND_PORT                   Flask backend port                (default: 8000)
#   FRONTEND_PORT                  Vite frontend port                (default: 5173)

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
BACKEND_PORT="${BACKEND_PORT:-8000}"
FRONTEND_PORT="${FRONTEND_PORT:-5173}"
VITE_PORT_OPT="--port ${FRONTEND_PORT}"

# ── Kill mode ──────────────────────────────────────────────────────────────────
if [ "${1:-}" = "--kill" ]; then
    echo "Stopping telemetry services (PID files)..."
    for pidfile in /tmp/chronon3d_flask.pid /tmp/chronon3d_vite.pid; do
        if [ -f "$pidfile" ]; then
            kill "$(cat "$pidfile")" 2>/dev/null || true
            rm -f "$pidfile"
        fi
    done
    echo "Done."
    exit 0
fi

# ── Generate/read password ─────────────────────────────────────────────────────
CHRONON3D_DASHBOARD_PASSWORD="${CHRONON3D_DASHBOARD_PASSWORD:-}"
if [ -z "$CHRONON3D_DASHBOARD_PASSWORD" ]; then
    # Auto-generate a disposable password for this session
    CHRONON3D_DASHBOARD_PASSWORD="$(date +%s | sha256sum | head -c 16)"
    echo "  Dashboard password: ${CHRONON3D_DASHBOARD_PASSWORD}"
    echo "  (Set CHRONON3D_DASHBOARD_PASSWORD env var to use a fixed password.)"
fi
export CHRONON3D_DASHBOARD_PASSWORD

# Kill leftover processes from previous runs (by PID file, not fuser)
for pidfile in /tmp/chronon3d_flask.pid /tmp/chronon3d_vite.pid; do
    if [ -f "$pidfile" ]; then
        kill "$(cat "$pidfile")" 2>/dev/null || true
        rm -f "$pidfile"
        sleep 0.5
    fi
done

echo "=== Chronon3D Telemetry Dashboard ==="
echo "  Backend port:  ${BACKEND_PORT}"
echo "  Frontend port: ${FRONTEND_PORT}"

# ── 1. Flask backend ───────────────────────────────────────────────────────────
echo "[1/2] Starting Flask backend on :${BACKEND_PORT}..."
cd "$DIR/tools/telemetry_dashboard"
setsid sh -c "CHRONON3D_DASHBOARD_PASSWORD=\"${CHRONON3D_DASHBOARD_PASSWORD}\" exec python3 server.py ${BACKEND_PORT}" \
    >/tmp/chronon3d_flask.log 2>&1 &
echo $! > /tmp/chronon3d_flask.pid

# ── 2. Vite frontend ──────────────────────────────────────────────────────────
echo "[2/2] Starting Vite frontend on :${FRONTEND_PORT}..."
cd "$DIR/tools/telemetry_dashboard/frontend"
setsid sh -c "VITE_BACKEND_PORT=${BACKEND_PORT} exec node ./node_modules/.bin/vite ${VITE_PORT_OPT}" \
    >/tmp/chronon3d_vite.log 2>&1 &
echo $! > /tmp/chronon3d_vite.pid

# ── Wait for both to be ready ──────────────────────────────────────────────────
echo "Waiting for services..."
BACKEND_OK=""
FRONTEND_OK=""
for i in $(seq 1 20); do
    BACKEND_OK=$(curl -s --max-time 2 -o /dev/null -w "%{http_code}" "http://localhost:${BACKEND_PORT}/api/runs" 2>/dev/null || true)
    FRONTEND_OK=$(curl -s --max-time 2 -o /dev/null -w "%{http_code}" "http://localhost:${FRONTEND_PORT}/" 2>/dev/null || true)
    if [ "$BACKEND_OK" = "200" ] && [ "$FRONTEND_OK" = "200" ]; then
        break
    fi
    sleep 1
done

# ── Status ─────────────────────────────────────────────────────────────────────
echo ""
if [ "$BACKEND_OK" = "200" ]; then
    echo "  Backend  [OK]  http://localhost:${BACKEND_PORT}"
else
    echo "  Backend  [FAIL] see /tmp/chronon3d_flask.log"
fi
if [ "$FRONTEND_OK" = "200" ]; then
    echo "  Frontend [OK]  http://localhost:${FRONTEND_PORT}"
else
    echo "  Frontend [FAIL] see /tmp/chronon3d_vite.log"
fi
echo ""
echo "  Stop:  ./start_telemetry.sh --kill"
echo "  Dashboard: http://localhost:${FRONTEND_PORT}/"
