// ---------------------------------------------------------------------------
// tests/backends/test_text_tile_raster_canary.cpp
//
// "TEST 123" canary for the GPU text tile path.
//
// Dispatches the EMBEDDED text_tile_bin / text_tile_raster SPIR-V (the exact
// bytes shipped in the backend) against a headless Vulkan device and verifies
// the two contracts that produced the visual-corruption blocker:
//
//   1. FORMAT QUALIFICATION — the raster shader declares dst_image as rgba32f
//      (destination surfaces are canonical RGBA32F storage images) and the
//      atlas as rgba8 (R8G8B8A8_UNORM / B8G8R8A8_UNORM).  Binding a real
//      R32G32B32A32_SFLOAT image view to the rgba32f-qualified SPIR-V must
//      execute cleanly and address the correct pixels; binding to the old
//      rgba8-qualified shader would fail validation / corrupt addressing.
//
//   2. PREMULTIPLIED COMPOSITE — source-over blending in the raster kernel is
//      result = src + dst * (1 - src.a) with premultiplied src.  A half-alpha
//      premultiplied atlas texel (rgb = 0.5, a = 0.5) over a known background
//      must produce 0.5 + bg * 0.5, NOT the straight-alpha result.
//
//   3. MTSDF ENCODING — glyphs flagged MTSDF take the screen-distance path
//      with tint premultiplication (rgb *= alpha).
//
// Skips silently when no Vulkan device (or no storage-image format support)
// is available, matching the descriptor-arena test convention.
// ---------------------------------------------------------------------------

#include <doctest/doctest.h>

#ifdef CHRONON3D_ENABLE_VULKAN

#include <vulkan/vulkan.h>

// Embedded SPIR-V of the kernels under test (generated by the shader build).
#include "text_tile_bin_comp_spv.hpp"
#include "text_tile_raster_comp_spv.hpp"

namespace shaders = chronon3d::backends::vulkan::shaders;

#include <array>
#include <cmath>
#include <cstring>
#include <vector>

namespace {

// ── Mirror of the backend's GpuGlyphStatic / GpuTextRunDynamic (std430) ──
struct GpuGlyphStatic {
    std::uint32_t run_index;
    std::uint32_t atlas_page_and_flags; // low 16: page, high 16: flags (bit0 = MTSDF)
    std::uint32_t atlas_pos;            // low 16: x, high 16: y
    std::uint32_t atlas_size;           // low 16: w, high 16: h
    float plane_left;
    float plane_top;
    float plane_right;
    float plane_bottom;
    std::uint32_t draw_order;
    std::uint32_t pad0;
    std::uint32_t pad1;
    std::uint32_t pad2;
};
static_assert(sizeof(GpuGlyphStatic) == 48);

struct GpuTextRunDynamic {
    float tx;
    float ty;
    float sx;
    float sy;
    float opacity;
    std::uint32_t color;
    float pad0;
    float pad1;
};
static_assert(sizeof(GpuTextRunDynamic) == 32);

struct RasterPush {
    std::uint32_t tiles_x;
    std::uint32_t tiles_y;
    std::uint32_t max_glyphs_per_tile;
    std::uint32_t dst_width;
    std::uint32_t dst_height;
    float atlas_inv_w;
    float atlas_inv_h;
};
static_assert(sizeof(RasterPush) == 28);

struct BinPush {
    std::uint32_t glyph_count;
    std::uint32_t tiles_x;
    std::uint32_t tiles_y;
    std::uint32_t max_glyphs_per_tile;
    std::uint32_t dst_width;
    std::uint32_t dst_height;
};
static_assert(sizeof(BinPush) == 24);

// ── Minimal headless device context ─────────────────────────────────────
struct DeviceContext {
    VkInstance instance{VK_NULL_HANDLE};
    VkPhysicalDevice physical{VK_NULL_HANDLE};
    VkDevice device{VK_NULL_HANDLE};
    VkQueue queue{VK_NULL_HANDLE};
    std::uint32_t queue_family{0};
    bool ok() const { return device != VK_NULL_HANDLE; }
};

DeviceContext make_device() {
    DeviceContext ctx;
    const VkApplicationInfo app{
        VK_STRUCTURE_TYPE_APPLICATION_INFO, nullptr, "Chronon3D text tile canary",
        VK_MAKE_VERSION(1, 0, 0), "Chronon3D", VK_MAKE_VERSION(1, 0, 0),
        VK_API_VERSION_1_1};
    const VkInstanceCreateInfo info{
        VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO, nullptr, 0, &app, 0, nullptr, 0, nullptr};
    if (vkCreateInstance(&info, nullptr, &ctx.instance) != VK_SUCCESS) return ctx;

    std::uint32_t count = 0;
    if (vkEnumeratePhysicalDevices(ctx.instance, &count, nullptr) != VK_SUCCESS || count == 0) {
        return ctx;
    }
    std::vector<VkPhysicalDevice> devices(count);
    vkEnumeratePhysicalDevices(ctx.instance, &count, devices.data());

    for (const auto pd : devices) {
        std::uint32_t fam_count = 0;
        vkGetPhysicalDeviceQueueFamilyProperties(pd, &fam_count, nullptr);
        std::vector<VkQueueFamilyProperties> fams(fam_count);
        vkGetPhysicalDeviceQueueFamilyProperties(pd, &fam_count, fams.data());
        for (std::uint32_t f = 0; f < fam_count; ++f) {
            if ((fams[f].queueFlags & VK_QUEUE_COMPUTE_BIT) != 0) {
                ctx.physical = pd;
                ctx.queue_family = f;
                break;
            }
        }
        if (ctx.physical != VK_NULL_HANDLE) break;
    }
    if (ctx.physical == VK_NULL_HANDLE) return ctx;

    constexpr float priority = 1.0f;
    const VkDeviceQueueCreateInfo queue{
        VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO, nullptr, 0,
        ctx.queue_family, 1, &priority};
    const VkDeviceCreateInfo dev{
        VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO, nullptr, 0, 1, &queue,
        0, nullptr, 0, nullptr, nullptr};
    if (vkCreateDevice(ctx.physical, &dev, nullptr, &ctx.device) != VK_SUCCESS) {
        ctx.device = VK_NULL_HANDLE;
        return ctx;
    }
    vkGetDeviceQueue(ctx.device, ctx.queue_family, 0, &ctx.queue);
    return ctx;
}

void destroy(DeviceContext& ctx) {
    if (ctx.device) vkDestroyDevice(ctx.device, nullptr);
    if (ctx.instance) vkDestroyInstance(ctx.instance, nullptr);
}

bool format_supports_storage(VkPhysicalDevice pd, VkFormat format) {
    VkFormatProperties props{};
    vkGetPhysicalDeviceFormatProperties(pd, format, &props);
    return (props.optimalTilingFeatures & VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT) != 0;
}

std::uint32_t find_memory(VkPhysicalDevice pd, std::uint32_t type_bits,
                          VkMemoryPropertyFlags wanted) {
    VkPhysicalDeviceMemoryProperties mem{};
    vkGetPhysicalDeviceMemoryProperties(pd, &mem);
    for (std::uint32_t i = 0; i < mem.memoryTypeCount; ++i) {
        if ((type_bits & (1u << i)) != 0 &&
            (mem.memoryTypes[i].propertyFlags & wanted) == wanted) {
            return i;
        }
    }
    return UINT32_MAX;
}

struct Buffer {
    VkDevice device{VK_NULL_HANDLE};
    VkBuffer handle{VK_NULL_HANDLE};
    VkDeviceMemory memory{VK_NULL_HANDLE};
    void* mapped{nullptr};
    VkDeviceSize size{0};

    void destroy() {
        if (handle) vkDestroyBuffer(device, handle, nullptr);
        if (memory) vkFreeMemory(device, memory, nullptr);
        handle = VK_NULL_HANDLE;
        memory = VK_NULL_HANDLE;
    }
};

Buffer make_host_buffer(VkDevice device, VkPhysicalDevice pd, VkDeviceSize size) {
    Buffer b;
    b.device = device;
    b.size = size;
    const VkBufferCreateInfo info{
        VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO, nullptr, 0, size,
        VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
        VK_SHARING_MODE_EXCLUSIVE};
    REQUIRE(vkCreateBuffer(device, &info, nullptr, &b.handle) == VK_SUCCESS);
    VkMemoryRequirements req{};
    vkGetBufferMemoryRequirements(device, b.handle, &req);
    const auto type = find_memory(pd, req.memoryTypeBits,
                                  VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                                      VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
    REQUIRE(type != UINT32_MAX);
    const VkMemoryAllocateInfo alloc{
        VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO, nullptr, req.size, type};
    REQUIRE(vkAllocateMemory(device, &alloc, nullptr, &b.memory) == VK_SUCCESS);
    REQUIRE(vkBindBufferMemory(device, b.handle, b.memory, 0) == VK_SUCCESS);
    REQUIRE(vkMapMemory(device, b.memory, 0, size, 0, &b.mapped) == VK_SUCCESS);
    return b;
}

struct Image {
    VkDevice device{VK_NULL_HANDLE};
    VkImage handle{VK_NULL_HANDLE};
    VkDeviceMemory memory{VK_NULL_HANDLE};
    VkImageView view{VK_NULL_HANDLE};
    VkFormat format{VK_FORMAT_UNDEFINED};
    std::uint32_t width{0};
    std::uint32_t height{0};

    void destroy() {
        if (view) vkDestroyImageView(device, view, nullptr);
        if (handle) vkDestroyImage(device, handle, nullptr);
        if (memory) vkFreeMemory(device, memory, nullptr);
        handle = VK_NULL_HANDLE;
        memory = VK_NULL_HANDLE;
    }
};

Image make_storage_image(VkDevice device, VkPhysicalDevice pd, std::uint32_t w,
                         std::uint32_t h, VkFormat format) {
    Image img;
    img.device = device;
    img.format = format;
    img.width = w;
    img.height = h;
    const VkImageCreateInfo info{
        VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO, nullptr, 0, VK_IMAGE_TYPE_2D,
        format, {w, h, 1}, 1, 1, VK_SAMPLE_COUNT_1_BIT, VK_IMAGE_TILING_OPTIMAL,
        VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT |
            VK_IMAGE_USAGE_STORAGE_BIT,
        VK_SHARING_MODE_EXCLUSIVE, VK_IMAGE_LAYOUT_UNDEFINED};
    REQUIRE(vkCreateImage(device, &info, nullptr, &img.handle) == VK_SUCCESS);
    VkMemoryRequirements req{};
    vkGetImageMemoryRequirements(device, img.handle, &req);
    const auto type = find_memory(pd, req.memoryTypeBits,
                                  VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    REQUIRE(type != UINT32_MAX);
    const VkMemoryAllocateInfo alloc{
        VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO, nullptr, req.size, type};
    REQUIRE(vkAllocateMemory(device, &alloc, nullptr, &img.memory) == VK_SUCCESS);
    REQUIRE(vkBindImageMemory(device, img.handle, img.memory, 0) == VK_SUCCESS);
    const VkImageViewCreateInfo view{
        VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO, nullptr, 0, img.handle,
        VK_IMAGE_VIEW_TYPE_2D, format, {VK_COMPONENT_SWIZZLE_IDENTITY,
            VK_COMPONENT_SWIZZLE_IDENTITY, VK_COMPONENT_SWIZZLE_IDENTITY,
            VK_COMPONENT_SWIZZLE_IDENTITY},
        {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1}};
    REQUIRE(vkCreateImageView(device, &view, nullptr, &img.view) == VK_SUCCESS);
    return img;
}

Buffer make_staging(VkDevice device, VkPhysicalDevice pd, VkDeviceSize size) {
    Buffer b;
    b.device = device;
    b.size = size;
    const VkBufferCreateInfo info{
        VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO, nullptr, 0, size,
        VK_BUFFER_USAGE_TRANSFER_SRC_BIT, VK_SHARING_MODE_EXCLUSIVE};
    REQUIRE(vkCreateBuffer(device, &info, nullptr, &b.handle) == VK_SUCCESS);
    VkMemoryRequirements req{};
    vkGetBufferMemoryRequirements(device, b.handle, &req);
    const auto type = find_memory(pd, req.memoryTypeBits,
                                  VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                                      VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
    REQUIRE(type != UINT32_MAX);
    const VkMemoryAllocateInfo alloc{
        VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO, nullptr, req.size, type};
    REQUIRE(vkAllocateMemory(device, &alloc, nullptr, &b.memory) == VK_SUCCESS);
    REQUIRE(vkBindBufferMemory(device, b.handle, b.memory, 0) == VK_SUCCESS);
    REQUIRE(vkMapMemory(device, b.memory, 0, size, 0, &b.mapped) == VK_SUCCESS);
    return b;
}

VkShaderModule make_module(VkDevice device, const std::uint8_t* data, std::size_t size) {
    const VkShaderModuleCreateInfo info{
        VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO, nullptr, 0, size,
        reinterpret_cast<const std::uint32_t*>(data)};
    VkShaderModule module = VK_NULL_HANDLE;
    REQUIRE(vkCreateShaderModule(device, &info, nullptr, &module) == VK_SUCCESS);
    return module;
}

void record_image_barrier(VkCommandBuffer cmd, const Image& img,
                          VkImageLayout old_layout, VkImageLayout new_layout,
                          VkAccessFlags src_access, VkAccessFlags dst_access,
                          VkPipelineStageFlags src_stage, VkPipelineStageFlags dst_stage) {
    const VkImageMemoryBarrier barrier{
        VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER, nullptr,
        src_access, dst_access, old_layout, new_layout,
        VK_QUEUE_FAMILY_IGNORED, VK_QUEUE_FAMILY_IGNORED,
        img.handle, {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1}};
    vkCmdPipelineBarrier(cmd, src_stage, dst_stage, 0, 0, nullptr, 0, nullptr, 1, &barrier);
}

// ── Canary scene ─────────────────────────────────────────────────────────
// Atlas 64x64 RGBA8:
//   glyph A (coverage/premultiplied) at (0,0) 8x8:
//     left 4 columns:  premultiplied white, alpha 1.0
//     right 4 columns: premultiplied white, alpha 0.5 (rgb = 0.5)
//   glyph B (MTSDF) at (8,0) 8x8: rgb = 1.0 (inside, dist +0.5), a = 255.
constexpr std::uint32_t kAtlasSize = 64;
constexpr std::uint32_t kDstSize = 64;
constexpr std::uint32_t kTilesX = kDstSize / 16;
constexpr std::uint32_t kTilesY = kDstSize / 16;
constexpr std::uint32_t kMaxGlyphsPerTile = 64;

struct Pixel { float r, g, b, a; };

Pixel background() { return {0.25f, 0.5f, 0.75f, 1.0f}; }

} // namespace

TEST_CASE("text tile path Vulkan canary (TEST 123)") {
    auto ctx = make_device();
    if (!ctx.ok()) {
        MESSAGE("No Vulkan compute device available; skipping text tile canary");
        return;
    }
    if (!format_supports_storage(ctx.physical, VK_FORMAT_R32G32B32A32_SFLOAT) ||
        !format_supports_storage(ctx.physical, VK_FORMAT_R8G8B8A8_UNORM)) {
        MESSAGE("Storage images in required formats unsupported; skipping canary");
        destroy(ctx);
        return;
    }

    // ── Resources ────────────────────────────────────────────────────────
    auto dst = make_storage_image(ctx.device, ctx.physical, kDstSize, kDstSize,
                                  VK_FORMAT_R32G32B32A32_SFLOAT);
    auto atlas = make_storage_image(ctx.device, ctx.physical, kAtlasSize,
                                    kAtlasSize, VK_FORMAT_R8G8B8A8_UNORM);

    // Glyph / run / tile-index buffers.
    std::array<GpuGlyphStatic, 2> glyphs{};
    // Glyph A: coverage/premultiplied, plane [4,8)x[4,8), run transform
    // (10,12) → screen rect x∈[14,18), y∈[16,20).  Spans tiles (0,1),(1,1).
    glyphs[0].run_index = 0;
    glyphs[0].atlas_page_and_flags = 0u; // flags bit0 = 0 → premultiplied RGBA
    glyphs[0].atlas_pos = 0u | (0u << 16);
    glyphs[0].atlas_size = 8u | (8u << 16);
    glyphs[0].plane_left = 4.0f;
    glyphs[0].plane_top = 4.0f;
    glyphs[0].plane_right = 8.0f;
    glyphs[0].plane_bottom = 8.0f;
    glyphs[0].draw_order = 0;
    // Glyph B: MTSDF, run (30,30) → screen x∈[34,38), y∈[34,38). Tile (2,2).
    glyphs[1].run_index = 1;
    glyphs[1].atlas_page_and_flags = 1u << 16; // flags bit0 = 1 → MTSDF
    glyphs[1].atlas_pos = 8u | (0u << 16);
    glyphs[1].atlas_size = 8u | (8u << 16);
    glyphs[1].plane_left = 4.0f;
    glyphs[1].plane_top = 4.0f;
    glyphs[1].plane_right = 8.0f;
    glyphs[1].plane_bottom = 8.0f;
    glyphs[1].draw_order = 1;

    std::array<GpuTextRunDynamic, 2> runs{};
    runs[0].tx = 10.0f; runs[0].ty = 12.0f;
    runs[0].sx = 1.0f; runs[0].sy = 1.0f;
    runs[0].opacity = 1.0f;
    runs[0].color = 0xFFFFFFFFu; // white/identity tint
    runs[1].tx = 30.0f; runs[1].ty = 30.0f;
    runs[1].sx = 1.0f; runs[1].sy = 1.0f;
    runs[1].opacity = 1.0f;
    runs[1].color = 0xFF0000FFu; // unpack_color → r=1,g=0,b=0,a=1 (red)

    const VkDeviceSize count_bytes = kTilesX * kTilesY * sizeof(std::uint32_t);
    const VkDeviceSize index_bytes = count_bytes * kMaxGlyphsPerTile;

    auto glyph_buf = make_host_buffer(ctx.device, ctx.physical, sizeof(glyphs));
    auto run_buf = make_host_buffer(ctx.device, ctx.physical, sizeof(runs));
    auto count_buf = make_host_buffer(ctx.device, ctx.physical, count_bytes);
    auto index_buf = make_host_buffer(ctx.device, ctx.physical, index_bytes);
    auto staging = make_staging(ctx.device, ctx.physical,
                                kAtlasSize * kAtlasSize * 4 + kDstSize * kDstSize * 16);
    std::memcpy(glyph_buf.mapped, glyphs.data(), sizeof(glyphs));
    std::memcpy(run_buf.mapped, runs.data(), sizeof(runs));
    std::memset(count_buf.mapped, 0, static_cast<std::size_t>(count_bytes));
    std::memset(index_buf.mapped, 0xFF, static_cast<std::size_t>(index_bytes));

    // Synthetic atlas upload.
    std::vector<std::uint8_t> atlas_pixels(static_cast<std::size_t>(kAtlasSize * kAtlasSize * 4), 0);
    for (std::uint32_t y = 0; y < 8; ++y) {
        for (std::uint32_t x = 0; x < 8; ++x) {
            const auto idx = (y * kAtlasSize + x) * 4;
            if (x < 4) {
                atlas_pixels[idx] = 255; atlas_pixels[idx + 1] = 255;
                atlas_pixels[idx + 2] = 255; atlas_pixels[idx + 3] = 255;
            } else {
                atlas_pixels[idx] = 128; atlas_pixels[idx + 1] = 128;
                atlas_pixels[idx + 2] = 128; atlas_pixels[idx + 3] = 128;
            }
        }
    }
    for (std::uint32_t y = 0; y < 8; ++y) {
        for (std::uint32_t x = 8; x < 16; ++x) {
            const auto idx = (y * kAtlasSize + x) * 4;
            atlas_pixels[idx] = 255; atlas_pixels[idx + 1] = 255;
            atlas_pixels[idx + 2] = 255; atlas_pixels[idx + 3] = 255;
        }
    }
    std::memcpy(staging.mapped, atlas_pixels.data(), atlas_pixels.size());

    // ── Pipelines & layouts ──────────────────────────────────────────────
    const VkDescriptorSetLayoutBinding bin_bindings[] = {
        {0, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, nullptr},
        {1, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, nullptr},
        {2, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, nullptr},
        {3, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, nullptr}};
    VkDescriptorSetLayout bin_layout = VK_NULL_HANDLE;
    const VkDescriptorSetLayoutCreateInfo bin_layout_info{
        VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO, nullptr, 0, 4, bin_bindings};
    REQUIRE(vkCreateDescriptorSetLayout(ctx.device, &bin_layout_info, nullptr,
                                        &bin_layout) == VK_SUCCESS);

    const VkDescriptorSetLayoutBinding raster_bindings[] = {
        {0, VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, 1, VK_SHADER_STAGE_COMPUTE_BIT, nullptr},
        {1, VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, 1, VK_SHADER_STAGE_COMPUTE_BIT, nullptr},
        {2, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, nullptr},
        {3, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, nullptr},
        {4, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, nullptr},
        {5, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, nullptr}};
    VkDescriptorSetLayout raster_layout = VK_NULL_HANDLE;
    const VkDescriptorSetLayoutCreateInfo raster_layout_info{
        VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO, nullptr, 0, 6, raster_bindings};
    REQUIRE(vkCreateDescriptorSetLayout(ctx.device, &raster_layout_info, nullptr,
                                        &raster_layout) == VK_SUCCESS);

    const VkPushConstantRange bin_push{VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(BinPush)};
    const VkPushConstantRange raster_push{VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(RasterPush)};
    VkPipelineLayout bin_pipeline_layout = VK_NULL_HANDLE;
    VkPipelineLayout raster_pipeline_layout = VK_NULL_HANDLE;
    const VkPipelineLayoutCreateInfo bin_pl_info{
        VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO, nullptr, 0, 1, &bin_layout,
        1, &bin_push};
    REQUIRE(vkCreatePipelineLayout(ctx.device, &bin_pl_info, nullptr,
                                   &bin_pipeline_layout) == VK_SUCCESS);
    const VkPipelineLayoutCreateInfo raster_pl_info{
        VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO, nullptr, 0, 1, &raster_layout,
        1, &raster_push};
    REQUIRE(vkCreatePipelineLayout(ctx.device, &raster_pl_info, nullptr,
                                   &raster_pipeline_layout) == VK_SUCCESS);

    VkShaderModule bin_module = make_module(
        ctx.device, shaders::chronon3d_text_tile_bin_comp_spv,
        shaders::chronon3d_text_tile_bin_comp_spv_size);
    VkShaderModule raster_module = make_module(
        ctx.device, shaders::chronon3d_text_tile_raster_comp_spv,
        shaders::chronon3d_text_tile_raster_comp_spv_size);

    const VkPipelineShaderStageCreateInfo bin_stage{
        VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO, nullptr, 0,
        VK_SHADER_STAGE_COMPUTE_BIT, bin_module, "main", nullptr};
    const VkPipelineShaderStageCreateInfo raster_stage{
        VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO, nullptr, 0,
        VK_SHADER_STAGE_COMPUTE_BIT, raster_module, "main", nullptr};

    VkPipeline bin_pipeline = VK_NULL_HANDLE;
    VkPipeline raster_pipeline = VK_NULL_HANDLE;
    const VkComputePipelineCreateInfo bin_ci{
        VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO, nullptr, 0,
        bin_stage, bin_pipeline_layout, VK_NULL_HANDLE, -1};
    REQUIRE(vkCreateComputePipelines(ctx.device, VK_NULL_HANDLE, 1, &bin_ci,
                                     nullptr, &bin_pipeline) == VK_SUCCESS);
    const VkComputePipelineCreateInfo raster_ci{
        VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO, nullptr, 0,
        raster_stage, raster_pipeline_layout, VK_NULL_HANDLE, -1};
    REQUIRE(vkCreateComputePipelines(ctx.device, VK_NULL_HANDLE, 1, &raster_ci,
                                     nullptr, &raster_pipeline) == VK_SUCCESS);

    // ── Descriptor sets ──────────────────────────────────────────────────
    VkDescriptorPool pool = VK_NULL_HANDLE;
    const VkDescriptorPoolSize pool_sizes[] = {
        {VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, 4},
        {VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 12}};
    const VkDescriptorPoolCreateInfo pool_info{
        VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO, nullptr, 0, 4, 2, pool_sizes};
    REQUIRE(vkCreateDescriptorPool(ctx.device, &pool_info, nullptr, &pool) == VK_SUCCESS);

    VkDescriptorSet bin_set = VK_NULL_HANDLE;
    VkDescriptorSet raster_set = VK_NULL_HANDLE;
    const VkDescriptorSetAllocateInfo bin_alloc{
        VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO, nullptr, pool, 1, &bin_layout};
    REQUIRE(vkAllocateDescriptorSets(ctx.device, &bin_alloc, &bin_set) == VK_SUCCESS);
    const VkDescriptorSetAllocateInfo raster_alloc{
        VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO, nullptr, pool, 1, &raster_layout};
    REQUIRE(vkAllocateDescriptorSets(ctx.device, &raster_alloc, &raster_set) == VK_SUCCESS);

    const VkDescriptorBufferInfo bg{glyph_buf.handle, 0, VK_WHOLE_SIZE};
    const VkDescriptorBufferInfo br{run_buf.handle, 0, VK_WHOLE_SIZE};
    const VkDescriptorBufferInfo bc{count_buf.handle, 0, VK_WHOLE_SIZE};
    const VkDescriptorBufferInfo bi{index_buf.handle, 0, VK_WHOLE_SIZE};
    const VkWriteDescriptorSet bin_writes[] = {
        {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, nullptr, bin_set, 0, 0, 1,
         VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, nullptr, &bg, nullptr},
        {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, nullptr, bin_set, 1, 0, 1,
         VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, nullptr, &br, nullptr},
        {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, nullptr, bin_set, 2, 0, 1,
         VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, nullptr, &bc, nullptr},
        {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, nullptr, bin_set, 3, 0, 1,
         VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, nullptr, &bi, nullptr}};
    vkUpdateDescriptorSets(ctx.device, 4, bin_writes, 0, nullptr);

    const VkDescriptorImageInfo dst_info{VK_NULL_HANDLE, dst.view, VK_IMAGE_LAYOUT_GENERAL};
    const VkDescriptorImageInfo atlas_info{VK_NULL_HANDLE, atlas.view, VK_IMAGE_LAYOUT_GENERAL};
    const VkWriteDescriptorSet raster_writes[] = {
        {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, nullptr, raster_set, 0, 0, 1,
         VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, &dst_info, nullptr, nullptr},
        {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, nullptr, raster_set, 1, 0, 1,
         VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, &atlas_info, nullptr, nullptr},
        {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, nullptr, raster_set, 2, 0, 1,
         VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, nullptr, &bg, nullptr},
        {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, nullptr, raster_set, 3, 0, 1,
         VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, nullptr, &br, nullptr},
        {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, nullptr, raster_set, 4, 0, 1,
         VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, nullptr, &bc, nullptr},
        {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, nullptr, raster_set, 5, 0, 1,
         VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, nullptr, &bi, nullptr}};
    vkUpdateDescriptorSets(ctx.device, 6, raster_writes, 0, nullptr);

    // ── Command buffer: clear dst, upload atlas, dispatch, read back ─────
    VkCommandPool cmd_pool = VK_NULL_HANDLE;
    const VkCommandPoolCreateInfo pool_ci{
        VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO, nullptr, 0, ctx.queue_family};
    REQUIRE(vkCreateCommandPool(ctx.device, &pool_ci, nullptr, &cmd_pool) == VK_SUCCESS);
    VkCommandBuffer cmd = VK_NULL_HANDLE;
    const VkCommandBufferAllocateInfo cmd_ai{
        VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO, nullptr, cmd_pool,
        VK_COMMAND_BUFFER_LEVEL_PRIMARY, 1};
    REQUIRE(vkAllocateCommandBuffers(ctx.device, &cmd_ai, &cmd) == VK_SUCCESS);

    const VkCommandBufferBeginInfo begin{
        VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO, nullptr,
        VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT, nullptr};
    REQUIRE(vkBeginCommandBuffer(cmd, &begin) == VK_SUCCESS);

    // Clear destination to the known background color.
    const Pixel bg_color = background();
    VkClearColorValue clear{};
    clear.float32[0] = bg_color.r;
    clear.float32[1] = bg_color.g;
    clear.float32[2] = bg_color.b;
    clear.float32[3] = bg_color.a;
    const VkImageSubresourceRange range{VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
    vkCmdClearColorImage(cmd, dst.handle, VK_IMAGE_LAYOUT_UNDEFINED, &clear, 1, &range);
    record_image_barrier(cmd, dst, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_GENERAL,
                         VK_ACCESS_TRANSFER_WRITE_BIT,
                         VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT,
                         VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT);

    // Copy atlas from staging.
    const VkBufferImageCopy copy{
        0, 0, 0, {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1}, {0, 0, 0},
        {kAtlasSize, kAtlasSize, 1}};
    vkCmdCopyBufferToImage(cmd, staging.handle, atlas.handle,
                           VK_IMAGE_LAYOUT_UNDEFINED, 1, &copy);
    record_image_barrier(cmd, atlas, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_GENERAL,
                         VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT,
                         VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT);

    // Bin.
    const BinPush bin_push_data{kTilesX * kTilesY > 0 ? 2u : 0u, kTilesX, kTilesY,
                                kMaxGlyphsPerTile, kDstSize, kDstSize};
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, bin_pipeline);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, bin_pipeline_layout,
                            0, 1, &bin_set, 0, nullptr);
    vkCmdPushConstants(cmd, bin_pipeline_layout, VK_SHADER_STAGE_COMPUTE_BIT, 0,
                       sizeof(BinPush), &bin_push_data);
    vkCmdDispatch(cmd, 1, 1, 1);

    // Bin → raster barrier over count/index buffers.
    const VkBufferMemoryBarrier bin_barriers[] = {
        {VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER, nullptr,
         VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT,
         VK_QUEUE_FAMILY_IGNORED, VK_QUEUE_FAMILY_IGNORED,
         count_buf.handle, 0, VK_WHOLE_SIZE},
        {VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER, nullptr,
         VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT,
         VK_QUEUE_FAMILY_IGNORED, VK_QUEUE_FAMILY_IGNORED,
         index_buf.handle, 0, VK_WHOLE_SIZE}};
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                         VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0,
                         0, nullptr, 2, bin_barriers, 0, nullptr);

    // Raster.
    const RasterPush raster_push_data{kTilesX, kTilesY, kMaxGlyphsPerTile,
                                      kDstSize, kDstSize,
                                      1.0f / static_cast<float>(kAtlasSize),
                                      1.0f / static_cast<float>(kAtlasSize)};
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, raster_pipeline);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, raster_pipeline_layout,
                            0, 1, &raster_set, 0, nullptr);
    vkCmdPushConstants(cmd, raster_pipeline_layout, VK_SHADER_STAGE_COMPUTE_BIT, 0,
                       sizeof(RasterPush), &raster_push_data);
    vkCmdDispatch(cmd, kTilesX, kTilesY, 1);

    // Copy destination back to staging for verification.
    record_image_barrier(cmd, dst, VK_IMAGE_LAYOUT_GENERAL, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                         VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT,
                         VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT);
    const VkBufferImageCopy read_copy{
        0, 0, 0, {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1}, {0, 0, 0},
        {kDstSize, kDstSize, 1}};
    vkCmdCopyImageToBuffer(cmd, dst.handle, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                           staging.handle, 1, &read_copy);
    REQUIRE(vkEndCommandBuffer(cmd) == VK_SUCCESS);

    VkFence fence = VK_NULL_HANDLE;
    const VkFenceCreateInfo fence_ci{
        VK_STRUCTURE_TYPE_FENCE_CREATE_INFO, nullptr, 0};
    REQUIRE(vkCreateFence(ctx.device, &fence_ci, nullptr, &fence) == VK_SUCCESS);
    const VkSubmitInfo submit{
        VK_STRUCTURE_TYPE_SUBMIT_INFO, nullptr, 0, nullptr, nullptr, 1, &cmd,
        0, nullptr};
    REQUIRE(vkQueueSubmit(ctx.queue, 1, &submit, fence) == VK_SUCCESS);
    REQUIRE(vkWaitForFences(ctx.device, 1, &fence, VK_TRUE, 5'000'000'000ull) == VK_SUCCESS);

    // ── Verification ─────────────────────────────────────────────────────
    const auto* pixels = static_cast<const Pixel*>(staging.mapped);
    const auto at = [&](std::uint32_t x, std::uint32_t y) {
        return pixels[y * kDstSize + x];
    };
    const auto near = [](float a, float b) { return std::fabs(a - b) < 0.01f; };
    const auto expected_bg = background();

    // Glyph A, full-alpha half (screen x 10..13, y 12..19; left half of atlas).
    const Pixel full = at(11, 14);
    CHECK(near(full.r, 1.0f));
    CHECK(near(full.g, 1.0f));
    CHECK(near(full.b, 1.0f));
    CHECK(near(full.a, 1.0f));

    // Glyph A, half-alpha half (screen x=16..17, y=14): premultiplied
    // 0.5 over background → 0.5 + bg * 0.5.  This is THE premultiplied
    // contract the tile raster must honor.
    const Pixel half = at(16, 14);
    CHECK(near(half.r, 0.5f + 0.5f * expected_bg.r));
    CHECK(near(half.g, 0.5f + 0.5f * expected_bg.g));
    CHECK(near(half.b, 0.5f + 0.5f * expected_bg.b));
    CHECK(near(half.a, 1.0f));

    // Glyph B, MTSDF red: tint premultiplied → (1, 0, 0, 1).
    const Pixel mtsdf = at(35, 35);
    CHECK(near(mtsdf.r, 1.0f));
    CHECK(near(mtsdf.g, 0.0f));
    CHECK(near(mtsdf.b, 0.0f));
    CHECK(near(mtsdf.a, 1.0f));

    // Untouched background outside the glyphs.
    const Pixel far_bg = at(0, 0);
    CHECK(near(far_bg.r, expected_bg.r));
    CHECK(near(far_bg.g, expected_bg.g));
    CHECK(near(far_bg.b, expected_bg.b));
    CHECK(near(far_bg.a, expected_bg.a));
    const Pixel just_outside = at(19, 14); // local x 9 ∉ [0, 8)
    CHECK(near(just_outside.r, expected_bg.r));
    CHECK(near(just_outside.g, expected_bg.g));
    CHECK(near(just_outside.b, expected_bg.b));
    CHECK(near(just_outside.a, expected_bg.a));

    // Tile binning sanity: the glyph A tiles must have received indices.
    const auto* counts = static_cast<const std::uint32_t*>(count_buf.mapped);
    CHECK(counts[0 * kTilesX + 0] >= 1); // tile (0,0) — glyph A covers [10,18)x[12,20)
    CHECK(counts[1 * kTilesX + 0] >= 1); // tile (0,1)
    CHECK(counts[1 * kTilesX + 1] >= 1); // tile (1,1)
    CHECK(counts[2 * kTilesX + 2] >= 1); // tile (2,2) — glyph B
    CHECK(counts[3 * kTilesX + 3] == 0); // tile (3,3) untouched

    vkDestroyFence(ctx.device, fence, nullptr);
    vkFreeCommandBuffers(ctx.device, cmd_pool, 1, &cmd);
    vkDestroyCommandPool(ctx.device, cmd_pool, nullptr);
    vkDestroyDescriptorPool(ctx.device, pool, nullptr);
    vkDestroyPipeline(ctx.device, bin_pipeline, nullptr);
    vkDestroyPipeline(ctx.device, raster_pipeline, nullptr);
    vkDestroyShaderModule(ctx.device, bin_module, nullptr);
    vkDestroyShaderModule(ctx.device, raster_module, nullptr);
    vkDestroyPipelineLayout(ctx.device, bin_pipeline_layout, nullptr);
    vkDestroyPipelineLayout(ctx.device, raster_pipeline_layout, nullptr);
    vkDestroyDescriptorSetLayout(ctx.device, bin_layout, nullptr);
    vkDestroyDescriptorSetLayout(ctx.device, raster_layout, nullptr);
    glyph_buf.destroy();
    run_buf.destroy();
    count_buf.destroy();
    index_buf.destroy();
    staging.destroy();
    dst.destroy();
    atlas.destroy();
    destroy(ctx);
}

#endif // CHRONON3D_ENABLE_VULKAN
