// ---------------------------------------------------------------------------
// tests/backends/test_shader_abi_consistency.cpp
//
// Verifies that each embedded compute shader's SPIR-V ABI (descriptor bindings,
// push-constant sizes, local workgroup sizes) matches the expected C++ constants
// used in the Vulkan backend implementation.
//
// This test introspects the embedded SPIR-V at runtime via spirv-reflect and
// compares against the hardcoded binding values from the backend.  If a shader
// is recompiled with different bindings or the C++ code is updated without
// updating this test, the build fails.
//
// Requires: CHRONON3D_ENABLE_VULKAN, spirv-reflect
// ---------------------------------------------------------------------------

#include <doctest/doctest.h>

#ifdef CHRONON3D_ENABLE_VULKAN

#include <spirv-reflect/spirv_reflect.h>

// Embedded SPIR-V headers (generated by chronon_add_compute_shader)
#include "composite_comp_spv.hpp"
#include "transform_comp_spv.hpp"
#include "affine_transform_comp_spv.hpp"
#include "blur_comp_spv.hpp"
#include "color_adjust_comp_spv.hpp"
#include "matte_comp_spv.hpp"
#include "text_run_comp_spv.hpp"
#include "fill_rect_comp_spv.hpp"
#include "layer_batch_comp_spv.hpp"
#include "text_batch_comp_spv.hpp"
#include "text_tile_bin_comp_spv.hpp"
#include "text_tile_raster_comp_spv.hpp"

// Generated ABI reflection headers (produced by tools/shaders/spirv_abi_gen)
#include "composite_abi.hpp"
#include "transform_abi.hpp"
#include "affine_transform_abi.hpp"
#include "blur_abi.hpp"
#include "color_adjust_abi.hpp"
#include "matte_abi.hpp"
#include "text_run_abi.hpp"
#include "fill_rect_abi.hpp"
#include "layer_batch_abi.hpp"
#include "text_batch_abi.hpp"
#include "text_tile_bin_abi.hpp"
#include "text_tile_raster_abi.hpp"

#include <algorithm>
#include <string>
#include <vector>

using namespace chronon3d::backends::vulkan::shaders;

// ── Reflection helpers ──────────────────────────────────────────────────

struct BindingInfo {
    std::uint32_t set;
    std::uint32_t binding;
    SpvReflectDescriptorType descriptor_type;
    std::string name;
};

struct ShaderAbi {
    std::uint32_t local_size_x{0};
    std::uint32_t local_size_y{0};
    std::uint32_t local_size_z{0};
    std::uint32_t push_constant_size{0};
    std::vector<BindingInfo> bindings;
};

static ShaderAbi reflect(const std::uint8_t* spv_data, std::size_t spv_size) {
    SpvReflectShaderModule module{};
    REQUIRE(spvReflectCreateShaderModule(spv_size, spv_data, &module) ==
            SPV_REFLECT_RESULT_SUCCESS);
    REQUIRE(module.entry_point_count > 0);
    REQUIRE(module.entry_points != nullptr);

    ShaderAbi abi;
    // The local workgroup size lives on the (single) entry point, not the module.
    const SpvReflectEntryPoint& ep = module.entry_points[0];
    abi.local_size_x = ep.local_size.x;
    abi.local_size_y = ep.local_size.y;
    abi.local_size_z = ep.local_size.z;

    // Descriptor bindings
    std::uint32_t count = 0;
    spvReflectEnumerateDescriptorBindings(&module, &count, nullptr);
    std::vector<SpvReflectDescriptorBinding*> raw_bindings(count);
    spvReflectEnumerateDescriptorBindings(&module, &count, raw_bindings.data());
    for (const auto* b : raw_bindings) {
        abi.bindings.push_back(BindingInfo{
            b->set, b->binding, b->descriptor_type,
            b->name ? b->name : "<unnamed>"});
    }
    // Sort by (set, binding) for deterministic comparison
    std::sort(abi.bindings.begin(), abi.bindings.end(),
              [](const BindingInfo& a, const BindingInfo& b) {
                  return a.set < b.set || (a.set == b.set && a.binding < b.binding);
              });

    // Push constants
    std::uint32_t push_count = 0;
    spvReflectEnumeratePushConstantBlocks(&module, &push_count, nullptr);
    if (push_count > 0) {
        std::vector<SpvReflectBlockVariable*> push_blocks(push_count);
        spvReflectEnumeratePushConstantBlocks(&module, &push_count, push_blocks.data());
        abi.push_constant_size = push_blocks[0]->size;
    }

    spvReflectDestroyShaderModule(&module);
    return abi;
}

// Helper: find a binding by set+index
static const BindingInfo* find_binding(const ShaderAbi& abi,
                                        std::uint32_t set, std::uint32_t binding) {
    for (const auto& b : abi.bindings) {
        if (b.set == set && b.binding == binding) return &b;
    }
    return nullptr;
}

// ── Descriptor layout expectations ──────────────────────────────────────
//
// The Vulkan backend uses a shared descriptor-set layout for most kernels
// (see vulkan_backend_lifecycle_private.cpp):
//   binding 0 = destination storage image
//   binding 1 = source / atlas storage image
//   binding 2 = matte storage image (matte kernel only)
//   binding 3 = storage buffer (glyph instances / layer instances)
//   binding 4 = storage buffer (text batch runs)
//
// text_tile_bin uses a separate layout (all storage buffers):
//   binding 0 = glyph buffer
//   binding 1 = run buffer
//   binding 2 = tile counts
//   binding 3 = tile indices
//
// text_tile_raster uses a separate layout:
//   binding 0 = destination image
//   binding 1 = atlas image
//   binding 2-5 = storage buffers

// ── Test cases ──────────────────────────────────────────────────────────

#define REFLECT_SHADER(name) \
    reflect(name, name##_size)

TEST_CASE("composite shader ABI") {
    auto abi = REFLECT_SHADER(chronon3d_composite_comp_spv);
    // Must have at least 2 storage-image bindings (dst, src)
    REQUIRE(find_binding(abi, 0, 0) != nullptr);
    CHECK(find_binding(abi, 0, 0)->descriptor_type == SPV_REFLECT_DESCRIPTOR_TYPE_STORAGE_IMAGE);
    REQUIRE(find_binding(abi, 0, 1) != nullptr);
    CHECK(find_binding(abi, 0, 1)->descriptor_type == SPV_REFLECT_DESCRIPTOR_TYPE_STORAGE_IMAGE);
    // workgroup size must be >= 1 in each dimension
    CHECK(abi.local_size_x >= 1);
    CHECK(abi.local_size_y >= 1);
    CHECK(abi.local_size_z == 1);
}

TEST_CASE("transform shader ABI") {
    auto abi = REFLECT_SHADER(chronon3d_transform_comp_spv);
    REQUIRE(find_binding(abi, 0, 0) != nullptr);
    REQUIRE(find_binding(abi, 0, 1) != nullptr);
}

TEST_CASE("affine_transform shader ABI") {
    auto abi = REFLECT_SHADER(chronon3d_affine_transform_comp_spv);
    REQUIRE(find_binding(abi, 0, 0) != nullptr);
    REQUIRE(find_binding(abi, 0, 1) != nullptr);
}

TEST_CASE("blur shader ABI") {
    auto abi = REFLECT_SHADER(chronon3d_blur_comp_spv);
    REQUIRE(find_binding(abi, 0, 0) != nullptr);
    REQUIRE(find_binding(abi, 0, 1) != nullptr);
}

TEST_CASE("color_adjust shader ABI") {
    auto abi = REFLECT_SHADER(chronon3d_color_adjust_comp_spv);
    REQUIRE(find_binding(abi, 0, 0) != nullptr);
    REQUIRE(find_binding(abi, 0, 1) != nullptr);
}

TEST_CASE("matte shader ABI") {
    auto abi = REFLECT_SHADER(chronon3d_matte_comp_spv);
    // matte uses 3 images: destination, target, matte
    REQUIRE(find_binding(abi, 0, 0) != nullptr);
    REQUIRE(find_binding(abi, 0, 1) != nullptr);
    REQUIRE(find_binding(abi, 0, 2) != nullptr);
}

TEST_CASE("text_run shader ABI") {
    auto abi = REFLECT_SHADER(chronon3d_text_run_comp_spv);
    // binding 0 = destination image, binding 1 = atlas image, binding 3 = glyph buffer
    REQUIRE(find_binding(abi, 0, 0) != nullptr);
    REQUIRE(find_binding(abi, 0, 1) != nullptr);
    // text_run uses binding 3 for its instance buffer
    auto* buf3 = find_binding(abi, 0, 3);
    REQUIRE(buf3 != nullptr);
    CHECK(buf3->descriptor_type == SPV_REFLECT_DESCRIPTOR_TYPE_STORAGE_BUFFER);
}

TEST_CASE("fill_rect shader ABI") {
    auto abi = REFLECT_SHADER(chronon3d_fill_rect_comp_spv);
    // fill_rect has only one image binding (destination)
    REQUIRE(find_binding(abi, 0, 0) != nullptr);
}

TEST_CASE("layer_batch shader ABI") {
    auto abi = REFLECT_SHADER(chronon3d_layer_batch_comp_spv);
    REQUIRE(find_binding(abi, 0, 0) != nullptr);
    REQUIRE(find_binding(abi, 0, 1) != nullptr);
    // layer_batch uses binding 3 for instance buffer
    REQUIRE(find_binding(abi, 0, 3) != nullptr);
}

TEST_CASE("text_batch shader ABI") {
    auto abi = REFLECT_SHADER(chronon3d_text_batch_comp_spv);
    REQUIRE(find_binding(abi, 0, 0) != nullptr);
    REQUIRE(find_binding(abi, 0, 1) != nullptr);
    // text_batch uses bindings 3 and 4 for glyph+run buffers
    REQUIRE(find_binding(abi, 0, 3) != nullptr);
    REQUIRE(find_binding(abi, 0, 4) != nullptr);
}

TEST_CASE("text_tile_bin shader ABI") {
    auto abi = REFLECT_SHADER(chronon3d_text_tile_bin_comp_spv);
    // text_tile_bin uses 4 storage buffers (glyph, run, counts, indices)
    REQUIRE(find_binding(abi, 0, 0) != nullptr);
    CHECK(find_binding(abi, 0, 0)->descriptor_type == SPV_REFLECT_DESCRIPTOR_TYPE_STORAGE_BUFFER);
    REQUIRE(find_binding(abi, 0, 1) != nullptr);
    REQUIRE(find_binding(abi, 0, 2) != nullptr);
    REQUIRE(find_binding(abi, 0, 3) != nullptr);
    // Must have no storage-image bindings
    for (const auto& b : abi.bindings) {
        CHECK_NE(b.descriptor_type, SPV_REFLECT_DESCRIPTOR_TYPE_STORAGE_IMAGE);
    }
}

TEST_CASE("text_tile_raster shader ABI") {
    auto abi = REFLECT_SHADER(chronon3d_text_tile_raster_comp_spv);
    // binding 0 = destination image, binding 1 = atlas image
    REQUIRE(find_binding(abi, 0, 0) != nullptr);
    CHECK(find_binding(abi, 0, 0)->descriptor_type == SPV_REFLECT_DESCRIPTOR_TYPE_STORAGE_IMAGE);
    REQUIRE(find_binding(abi, 0, 1) != nullptr);
    CHECK(find_binding(abi, 0, 1)->descriptor_type == SPV_REFLECT_DESCRIPTOR_TYPE_STORAGE_IMAGE);
    // bindings 2-5 are storage buffers
    REQUIRE(find_binding(abi, 0, 2) != nullptr);
    REQUIRE(find_binding(abi, 0, 3) != nullptr);
    REQUIRE(find_binding(abi, 0, 4) != nullptr);
    REQUIRE(find_binding(abi, 0, 5) != nullptr);
}

// ── Generated ABI headers vs runtime reflection ─────────────────────────
// The build runs tools/shaders/spirv_abi_gen against the same .spv bytes
// embedded here.  A generated ABI header and the runtime reflection MUST
// agree — if they diverge, either the codegen tool is stale or the embedded
// SPIR-V was regenerated without re-running codegen.
TEST_CASE("generated ABI headers match runtime reflection") {
    auto composite_abi = REFLECT_SHADER(chronon3d_composite_comp_spv);
    CHECK(composite_abi.local_size_x == CompositeShaderAbi::kLocalSizeX);
    CHECK(composite_abi.local_size_y == CompositeShaderAbi::kLocalSizeY);
    CHECK(composite_abi.local_size_z == CompositeShaderAbi::kLocalSizeZ);

    auto tile_raster_abi = REFLECT_SHADER(chronon3d_text_tile_raster_comp_spv);
    CHECK(tile_raster_abi.local_size_x == TextTileRasterShaderAbi::kLocalSizeX);
    CHECK(tile_raster_abi.local_size_y == TextTileRasterShaderAbi::kLocalSizeY);
    CHECK(tile_raster_abi.local_size_z == TextTileRasterShaderAbi::kLocalSizeZ);
}

#endif // CHRONON3D_ENABLE_VULKAN