// ═══════════════════════════════════════════════════════════════════════════
// bench_corpus_scenes.cpp — 12-scene benchmark corpus implementations.
//
// TICKET-BENCH-CORPUS-V1 — see bench_corpus_scenes.hpp for the contract
// and the B00-B11 per-scene expectation matrices.
//
// All 12 factories are pure (FrameContext → Scene, no time-of-day or
// unseeded RNG state), so the 11/11 baseline suite tests stay bit-
// identical across invocations.
//
// Cat-3 minimal-surface: ZERO new public SDK symbols; pure re-use of
// existing `Composition` + `SceneBuilder` + `LayerBuilder` surface.
// ═══════════════════════════════════════════════════════════════════════════

#include "bench_corpus_scenes.hpp"

#include <chronon3d/core/composition/composition_registry.hpp>
#include <chronon3d/timeline/composition_descriptor.hpp>
#include <chronon3d/scene/builders/scene_builder.hpp>
#include <chronon3d/scene/builders/layer_builder.hpp>
#include <chronon3d/presets/scene_presets.hpp>
#include <chronon3d/timeline/composition.hpp>
#include <chronon3d/timeline/composition_props.hpp>

// TICKET-CHRONON-GLOW-FINAL — canonical glow factory (header-only).
// Same include path used by apps/chronon3d_cli/register_runtime_compositions.cpp.
// Reuse, not duplication — the production factory IS the benchmark.
#include "content/compositions/chronon_glow_final.hpp"

namespace chronon3d::bench_corpus {

namespace {

// ── scene_presets::detail shorthand aliases (Cat-3: re-use, no new helpers) ──
using chronon3d::scene_presets::detail::default_font;
using chronon3d::scene_presets::detail::text_preset;

// Common background factory for dark canvases (reused across B03/B07/B09/B10).
inline void add_dark_canvas_background(SceneBuilder& s) {
    s.screen_layer("bg", [](LayerBuilder& l) {
        l.rect("fill", {
            .size = {1920.0f, 1080.0f},
            .color = {0.01f, 0.015f, 0.025f, 1.0f},
            .fill = chronon3d::FillStyle::linear(
                {0.0f, 0.0f}, {0.0f, 1.0f}, {
                    {chronon3d::graphics::GradientStop{0.0f, {0.04f, 0.03f, 0.10f, 1.0f}}},
                    {chronon3d::graphics::GradientStop{1.0f, {0.01f, 0.01f, 0.03f, 1.0f}}},
                }),
        });
    });
    s.screen_layer("deep_glow", [](LayerBuilder& l) {
        l.blend(BlendMode::Add);
        l.opacity(0.20f);
        l.circle("glow", {
            .radius = 380.0f,
            .color = {0.25f, 0.12f, 0.65f, 0.15f},
            .pos = {0.0f, 0.0f, 0.0f},
        });
    });
}

} // anonymous namespace

// ── B00 — EmptyFrame ────────────────────────────────────────────────────
Composition bench_b00_empty_frame() {
    return composition({
        .name = "BenchB00_EmptyFrame",
        .width = 1920, .height = 1080,
        .frame_rate = {30, 1},
        .duration = 1,
    }, [](const FrameContext& ctx) -> Scene {
        SceneBuilder s(ctx);
        // Deliberately empty: NO layers added.
        return s.build();
    });
}

// ── B01 — StaticText1080p ──────────────────────────────────────────────
Composition bench_b01_static_text_1080p() {
    return composition({
        .name = "BenchB01_StaticText1080p",
        .width = 1920, .height = 1080,
        .frame_rate = {30, 1},
        .duration = 90,
    }, [](const FrameContext& ctx) -> Scene {
        SceneBuilder s(ctx);
        if (ctx.runtime && ctx.runtime->font_engine()) s.font_engine(ctx.runtime->font_engine());

        add_dark_canvas_background(s);

        s.layer("title", [](LayerBuilder& l) {
            l.screen_dimensions(1920.0f, 1080.0f);
            l.text("title", text_preset(
                "CHRONON BENCH", 128.0f, 900,
                {1.0f, 1.0f, 1.0f, 1.0f},
                TextAlign::Center, {1600.0f, 200.0f}, {0.0f, 0.0f, 0.0f}
            ));
        });
        return s.build();
    });
}

// ── B02 — Typewriter200Glyphs ──────────────────────────────────────────
Composition bench_b02_typewriter_200_glyphs() {
    return composition({
        .name = "BenchB02_Typewriter200Glyphs",
        .width = 1920, .height = 1080,
        .frame_rate = {30, 1},
        .duration = 90,
    }, [](const FrameContext& ctx) -> Scene {
        SceneBuilder s(ctx);
        if (ctx.runtime && ctx.runtime->font_engine()) s.font_engine(ctx.runtime->font_engine());

        add_dark_canvas_background(s);

        // 200-character string for the typewriter exercise (deterministic)
        // — generated by repeating a Latin pangram pattern.
        std::string typewriter_text;
        static constexpr char kPangram[] =
            "Chronon 3D is a deterministic CPU-only video renderer. "
            "Quick brown fox jumps over the lazy dog. Pack my box with "
            "five dozen liquor jugs. The five boxing wizards jump quickly.";
        for (int i = 0; i < 4; ++i) {
            typewriter_text += kPangram;
        }
        // Trim to exactly 200 glyphs (round number for indexing reports).
        if (typewriter_text.size() > 200) typewriter_text.resize(200);

        TextAnimator ta;
        ta.text(typewriter_text)
          .font_size(48.0f)
          .font_path(default_font())
          .font_weight(700)
          .color({1.0f, 1.0f, 1.0f, 1.0f})
          .align(TextAlign::Left)
          .config({
              .mode = TextAnimMode::ByCharacter,
              .duration = Frame{20},
              .delay_per_unit = Frame{2},
              .easing = EasingCurve{Easing::OutCubic},
              .animate_opacity = true,
              .animate_slide = false,
              .slide_from = {0.0f, 0.0f, 0.0f},
              .animate_scale = false,
              .scale_from = {1.0f, 1.0f, 1.0f},
          });
        ta.build(s, "typewriter");

        return s.build();
    });
}

// ── B03 — CinematicGlow1080p ────────────────────────────────────────────
Composition bench_b03_cinematic_glow_1080p() {
    return composition({
        .name = "BenchB03_CinematicGlow1080p",
        .width = 1920, .height = 1080,
        .frame_rate = {30, 1},
        .duration = 90,
    }, [](const FrameContext&) -> Scene {
        // Reuse the canonical production glow factory (header-only,
        // no duplicated timeline / scene / text logic — Cat-3 anti-dup).
        auto p = chronon3d::content::glow_final::default_landscape_props();
        return chronon3d::content::glow_final::make_chronon_glow_final(p);
    });
}

// ── B04 — Layers100 ────────────────────────────────────────────────────
Composition bench_b04_layers_100() {
    return composition({
        .name = "BenchB04_Layers100",
        .width = 1920, .height = 1080,
        .frame_rate = {30, 1},
        .duration = 90,
    }, [](const FrameContext& ctx) -> Scene {
        SceneBuilder s(ctx);
        s.screen_layer("bg", [](LayerBuilder& l) {
            l.fill(Color{0.05f, 0.05f, 0.08f, 1.0f});
        });

        // 100 independent layers; each is a rounded_rect with its own
        // position grid + opacity stagger + scale overshoot.
        for (int i = 0; i < 100; ++i) {
            const int row = i / 10;
            const int col = i % 10;
            const f32 x = (static_cast<f32>(col) - 4.5f) * 180.0f;
            const f32 y = (static_cast<f32>(row) - 4.5f) * 100.0f;
            const Frame delay = Frame{static_cast<Frame>(i % 60)};

            s.layer("L" + std::to_string(i), [&, i, x, y, delay](LayerBuilder& l) {
                l.position({x, y, 0.0f});
                l.rounded_rect("rect", {
                    .size = {120.0f, 60.0f},
                    .radius = 8.0f,
                    .color = {0.20f + (i % 10) * 0.05f,
                              0.40f + (i % 7)  * 0.04f,
                              0.80f, 0.85f},
                    .fill = std::nullopt,
                });
                auto& op = l.opacity_anim();
                op.key(Frame{0}, 0.0f, EasingCurve{Easing::Hold});
                op.key(delay,    0.0f, EasingCurve{Easing::OutCubic});
                op.key(delay + Frame{15}, 1.0f, EasingCurve{Easing::Linear});
                l.settle(0.06f, Frame{10});
            });
        }
        return s.build();
    });
}

// ── B05 — Blur4K ────────────────────────────────────────────────────────
Composition bench_b05_blur_4k() {
    return composition({
        .name = "BenchB05_Blur4K",
        .width = 3840, .height = 2160,
        .frame_rate = {30, 1},
        .duration = 90,
    }, [](const FrameContext& ctx) -> Scene {
        SceneBuilder s(ctx);
        s.screen_layer("bg", [](LayerBuilder& l) {
            l.fill(Color{0.02f, 0.02f, 0.05f, 1.0f});
        });

        s.layer("blurred_canvas", [](LayerBuilder& l) {
            l.screen_dimensions(3840.0f, 2160.0f);
            l.rect("full", {
                .size = {3840.0f, 2160.0f},
                .color = {0.30f, 0.55f, 1.0f, 0.50f},
                .fill = std::nullopt,
            });
            // Heavy blur — 48px radius on a 4K canvas. Pure
            // memory-bandwidth stress + kernel cache behavior test.
            l.blur(48.0f);
        });
        return s.build();
    });
}

// ── B06 — VideoOverlay1080p ─────────────────────────────────────────────
// Static fallback image overlay (camera_reference.jpg) + centered text
// overlay. The bench runner can substitute a real mp4 when assets/
// videos/dummy.mp4 exists; otherwise the static image exercises the
// same decode+composite path without codec dependency.
Composition bench_b06_video_overlay_1080p() {
    return composition({
        .name = "BenchB06_VideoOverlay1080p",
        .width = 1920, .height = 1080,
        .frame_rate = {30, 1},
        .duration = 90,
    }, [](const FrameContext& ctx) -> Scene {
        SceneBuilder s(ctx);
        if (ctx.runtime && ctx.runtime->font_engine()) s.font_engine(ctx.runtime->font_engine());

        // Base image layer (the "video" surrogate for offline CI runs).
        s.layer("video_layer", [](LayerBuilder& l) {
            l.screen_dimensions(1920.0f, 1080.0f);
            l.opacity(0.85f);
            l.image("frame", ImageParams{
                .asset_path = "assets/images/camera_reference.jpg",
                .size = {1920.0f, 1080.0f},
                .pos = {0.0f, 0.0f, 0.0f},
                .fit = FitMode::Cover,
                .focal_point = {0.5f, 0.5f},
                .crop = {},
                .opacity = 1.0f,
                .radius = 0.0f,
            });
        });

        // Text overlay (centered, white, large).
        s.layer("overlay_text", [](LayerBuilder& l) {
            l.position({0.0f, 380.0f, 0.0f});
            l.text("caption", text_preset(
                "CHRONON · OVERLAY", 64.0f, 800,
                {1.0f, 1.0f, 1.0f, 1.0f},
                TextAlign::Center, {1400.0f, 100.0f}, {0.0f, 0.0f, 0.0f}
            ));
            l.drop_shadow({0.0f, 8.0f}, {0.0f, 0.0f, 0.0f, 0.55f}, 18.0f);
            l.fade_in(Frame{15}, EasingCurve{Easing::OutCubic});
        });
        return s.build();
    });
}

// ── B07 — NestedPrecomps ───────────────────────────────────────────────
// 3 levels of nested precomps, each level with 5 primitives. The
// inner precomps (BenchB07Inner_A / _B / _C) are also registered so the
// outer composition's `precomp()` references resolve at evaluation
// time. Total: 12 main + 3 inner = 15 registry entries.
namespace bench_b07_inner {

Composition inner_a() {
    return composition({
        .name = "BenchB07InnerA",
        .width = 1280, .height = 720,
        .frame_rate = {30, 1},
        .duration = 90,
    }, [](const FrameContext& ctx) -> Scene {
        SceneBuilder s(ctx);
        if (ctx.runtime && ctx.runtime->font_engine()) s.font_engine(ctx.runtime->font_engine());
        s.screen_layer("bg_a", [](LayerBuilder& l) {
            l.fill(Color{0.10f, 0.10f, 0.20f, 1.0f});
        });
        for (int i = 0; i < 5; ++i) {
            s.layer("a_" + std::to_string(i), [i](LayerBuilder& l) {
                l.position({static_cast<f32>(i) * 200.0f - 400.0f, 0.0f, 0.0f});
                l.opacity(static_cast<f32>(i + 1) / 5.0f);
                l.circle("dot", {
                    .radius = 30.0f,
                    .color = {0.6f, 0.8f, 1.0f, 0.5f},
                    .pos = {0.0f, 0.0f, 0.0f},
                });
            });
        }
        return s.build();
    });
}

Composition inner_b() {
    return composition({
        .name = "BenchB07InnerB",
        .width = 1280, .height = 720,
        .frame_rate = {30, 1},
        .duration = 90,
    }, [](const FrameContext& ctx) -> Scene {
        SceneBuilder s(ctx);
        if (ctx.runtime && ctx.runtime->font_engine()) s.font_engine(ctx.runtime->font_engine());
        s.screen_layer("bg_b", [](LayerBuilder& l) {
            l.fill(Color{0.20f, 0.10f, 0.10f, 1.0f});
        });
        for (int i = 0; i < 5; ++i) {
            s.layer("b_" + std::to_string(i), [i](LayerBuilder& l) {
                l.position({0.0f, static_cast<f32>(i) * 100.0f - 200.0f, 0.0f});
                l.rounded_rect("rect", {
                    .size = {180.0f, 50.0f},
                    .radius = 12.0f,
                    .color = {1.0f, 0.7f, 0.3f, 0.6f},
                    .fill = std::nullopt,
                });
                l.text("label", text_preset(
                    "B" + std::to_string(i), 18.0f, 700,
                    {1.0f, 1.0f, 1.0f, 1.0f},
                    TextAlign::Center, {180.0f, 50.0f}, {0.0f, 0.0f, 0.0f}
                ));
            });
        }
        return s.build();
    });
}

Composition inner_c() {
    return composition({
        .name = "BenchB07InnerC",
        .width = 1280, .height = 720,
        .frame_rate = {30, 1},
        .duration = 90,
    }, [](const FrameContext& ctx) -> Scene {
        SceneBuilder s(ctx);
        if (ctx.runtime && ctx.runtime->font_engine()) s.font_engine(ctx.runtime->font_engine());
        s.screen_layer("bg_c", [](LayerBuilder& l) {
            l.fill(Color{0.05f, 0.20f, 0.10f, 1.0f});
        });
        for (int i = 0; i < 5; ++i) {
            s.layer("c_" + std::to_string(i), [i](LayerBuilder& l) {
                l.position({static_cast<f32>(i) * 240.0f - 480.0f,
                            static_cast<f32>(i) * 120.0f - 240.0f, 0.0f});
                l.opacity(static_cast<f32>(5 - i) / 5.0f);
                l.star("star", {
                    .size = {80.0f, 80.0f},
                    .color = {1.0f, 1.0f, 0.5f, 0.7f},
                });
            });
        }
        return s.build();
    });
}

} // namespace bench_b07_inner

Composition bench_b07_nested_precomps() {
    return composition({
        .name = "BenchB07_NestedPrecomps",
        .width = 1920, .height = 1080,
        .frame_rate = {30, 1},
        .duration = 90,
    }, [](const FrameContext& ctx) -> Scene {
        SceneBuilder s(ctx);
        add_dark_canvas_background(s);

        // 3-level nesting: outer precomp (this composition) holds 3
        // mid-level precomps (A/B/C). Each mid-level precomp is a
        // standalone composition registered under BenchB07InnerA/B/C
        // and contains 5 primitives. The OPP graph compiler must
        // resolve 3 levels of compositional caching.
        s.precomp_layer("pA", "BenchB07InnerA", [](LayerBuilder& l) {
            (void)l;  // precomp-level primitive customization hook
        });
        s.precomp_layer("pB", "BenchB07InnerB", [](LayerBuilder& l) {
            (void)l;
        });
        s.precomp_layer("pC", "BenchB07InnerC", [](LayerBuilder& l) {
            (void)l;
        });
        return s.build();
    });
}

// ── B08 — DirtyRectSmallMotion ─────────────────────────────────────────
Composition bench_b08_dirty_rect_small_motion() {
    return composition({
        .name = "BenchB08_DirtyRectSmallMotion",
        .width = 1920, .height = 1080,
        .frame_rate = {30, 1},
        .duration = 90,
    }, [](const FrameContext& ctx) -> Scene {
        SceneBuilder s(ctx);
        if (ctx.runtime && ctx.runtime->font_engine()) s.font_engine(ctx.runtime->font_engine());

        add_dark_canvas_background(s);

        // Static footer (anchored to bottom edge, no animation). This
        // SHOULD never be marked dirty across the 90 frames — the
        // dirty_rect tracker can drop it from the per-frame worklist.
        s.screen_layer("static_footer", [](LayerBuilder& l) {
            l.position({0.0f, 480.0f, 0.0f});
            l.text("footer", text_preset(
                "static baseline", 24.0f, 400,
                {0.5f, 0.55f, 0.65f, 0.7f},
                TextAlign::Center, {1200.0f, 40.0f}, {0.0f, 0.0f, 0.0f}
            ));
        });

        // Single moving bbox — 240×160 rect that fades+slides over
        // frames 0..90. Only this rect should be marked dirty each
        // frame; the rest of the canvas must stay IDENTICAL.
        s.layer("motion_box", [](LayerBuilder& l) {
            l.position({0.0f, -60.0f, 0.0f});
            l.rounded_rect("box", {
                .size = {240.0f, 160.0f},
                .radius = 12.0f,
                .color = {0.85f, 0.30f, 0.40f, 1.0f},
                .fill = chronon3d::FillStyle::radial(
                    {0.5f, 0.5f}, 0.6f, {
                        {chronon3d::graphics::GradientStop{0.0f, {1.0f, 0.6f, 0.4f, 1.0f}}},
                        {chronon3d::graphics::GradientStop{1.0f, {0.6f, 0.2f, 0.3f, 0.8f}}},
                    }),
            });
            // Slide down from Frame{15}..Frame{60}; opacity fade-in start.
            auto& pos = l.position_anim();
            pos.key(Frame{0},  Vec3{0.0f, -60.0f, 0.0f}, EasingCurve{Easing::Hold});
            pos.key(Frame{15}, Vec3{0.0f, -60.0f, 0.0f}, EasingCurve{Easing::OutCubic});
            pos.key(Frame{60}, Vec3{0.0f,  60.0f, 0.0f}, EasingCurve{Easing::Linear});
            auto& op = l.opacity_anim();
            op.key(Frame{0}, 0.0f, EasingCurve{Easing::Hold});
            op.key(Frame{15}, 0.0f, EasingCurve{Easing::OutCubic});
            op.key(Frame{30}, 1.0f, EasingCurve{Easing::Linear});
        });
        return s.build();
    });
}

// ── B09 — LongForm10Minutes ────────────────────────────────────────────
Composition bench_b09_long_form_10_minutes() {
    return composition({
        .name = "BenchB09_LongForm10Minutes",
        .width = 1920, .height = 1080,
        .frame_rate = {30, 1},
        .duration = 18000,  // 10 minutes @ 30 fps
    }, [](const FrameContext& ctx) -> Scene {
        SceneBuilder s(ctx);
        if (ctx.runtime && ctx.runtime->font_engine()) s.font_engine(ctx.runtime->font_engine());

        // Pure static background; the long-form test is about LEAK
        // detection + ALLOCATOR FRAGMENTATION in the kernel hot path
        // across sustained rendering, NOT about scene complexity.
        s.screen_layer("screen_bg", [](LayerBuilder& l) {
            l.fill(Color{0.04f, 0.04f, 0.06f, 1.0f});
        });
        s.layer("title", [](LayerBuilder& l) {
            l.position({0.0f, 0.0f, 0.0f});
            l.text("title", text_preset(
                "CHRONON · LONG-FORM", 96.0f, 700,
                {0.85f, 0.87f, 0.92f, 0.95f},
                TextAlign::Center, {1400.0f, 110.0f}, {0.0f, 0.0f, 0.0f}
            ));
            // Single fade-in animation; rest of the timeline is static.
            l.fade_in(Frame{15}, EasingCurve{Easing::OutCubic});
        });
        return s.build();
    });
}

// ── B10 — RandomFrameAccess ────────────────────────────────────────────
Composition bench_b10_random_frame_access() {
    return composition({
        .name = "BenchB10_RandomFrameAccess",
        .width = 1920, .height = 1080,
        .frame_rate = {30, 1},
        .duration = 360,
    }, [](const FrameContext& ctx) -> Scene {
        SceneBuilder s(ctx);
        if (ctx.runtime && ctx.runtime->font_engine()) s.font_engine(ctx.runtime->font_engine());

        add_dark_canvas_background(s);

        // Static reference markers at canonical positions — the
        // frame-cache-coherence test reads them back to verify
        // random frame index access produces the same content as
        // sequential access.
        for (int i = 0; i < 4; ++i) {
            s.layer("marker_" + std::to_string(i), [i](LayerBuilder& l) {
                const f32 x = (i == 0) ? -700.0f : (i == 1) ? -250.0f
                                   : (i == 2) ?  250.0f :  700.0f;
                l.position({x, 200.0f, 0.0f});
                l.circle("dot", {
                    .radius = 30.0f,
                    .color = {0.5f, 0.85f, 1.0f, 0.7f},
                    .pos = {0.0f, 0.0f, 0.0f},
                });
                l.text("label", text_preset(
                    "M" + std::to_string(i), 18.0f, 700,
                    {1.0f, 1.0f, 1.0f, 1.0f},
                    TextAlign::Center, {120.0f, 30.0f}, {0.0f, 50.0f, 0.0f}
                ));
            });
        }
        return s.build();
    });
}

// ── B11 — Portrait1080x1920 ────────────────────────────────────────────
Composition bench_b11_portrait_1080x1920() {
    return composition({
        .name = "BenchB11_Portrait1080x1920",
        .width = 1080, .height = 1920,
        .frame_rate = {30, 1},
        .duration = 90,
    }, [](const FrameContext&) -> Scene {
        // Reuse the canonical portrait glow factory. The portrait
        // factory uses the SAME make_chronon_glow_final() entry
        // point as the landscape — only the default props differ.
        auto p = chronon3d::content::glow_final::default_portrait_props();
        return chronon3d::content::glow_final::make_chronon_glow_final(p);
    });
}

// ── Registry entry point ─────────────────────────────────────────────────
// Single function: register all 12 main scenes + 3 B07 inner scenes
// into the CompositionRegistry. Uses the `add(CompositionDescriptor{.factory, ...})`
// canonical entry — descriptor-first metadata so future tooling can
// inspect scene properties without instantiating the Composition.
void register_bench_corpus_compositions(CompositionRegistry& registry) {
    using Desc = chronon3d::CompositionDescriptor;

    registry.add(Desc{
        .id          = "BenchB00_EmptyFrame",
        .factory     = [](const chronon3d::CompositionProps&) {
            return bench_b00_empty_frame();
        },
        .category    = "bench/baseline",
    });
    registry.add(Desc{
        .id          = "BenchB01_StaticText1080p",
        .factory     = [](const chronon3d::CompositionProps&) {
            return bench_b01_static_text_1080p();
        },
        .category    = "bench/text",
    });
    registry.add(Desc{
        .id          = "BenchB02_Typewriter200Glyphs",
        .factory     = [](const chronon3d::CompositionProps&) {
            return bench_b02_typewriter_200_glyphs();
        },
        .category    = "bench/text",
    });
    registry.add(Desc{
        .id          = "BenchB03_CinematicGlow1080p",
        .factory     = [](const chronon3d::CompositionProps&) {
            return bench_b03_cinematic_glow_1080p();
        },
        .category    = "bench/glow",
    });
    registry.add(Desc{
        .id          = "BenchB04_Layers100",
        .factory     = [](const chronon3d::CompositionProps&) {
            return bench_b04_layers_100();
        },
        .category    = "bench/layers",
    });
    registry.add(Desc{
        .id          = "BenchB05_Blur4K",
        .factory     = [](const chronon3d::CompositionProps&) {
            return bench_b05_blur_4k();
        },
        .category    = "bench/memory",
    });
    registry.add(Desc{
        .id          = "BenchB06_VideoOverlay1080p",
        .factory     = [](const chronon3d::CompositionProps&) {
            return bench_b06_video_overlay_1080p();
        },
        .category    = "bench/asset",
    });
    registry.add(Desc{
        .id          = "BenchB07_NestedPrecomps",
        .factory     = [](const chronon3d::CompositionProps&) {
            return bench_b07_nested_precomps();
        },
        .category    = "bench/graph",
    });
    registry.add(Desc{
        .id          = "BenchB08_DirtyRectSmallMotion",
        .factory     = [](const chronon3d::CompositionProps&) {
            return bench_b08_dirty_rect_small_motion();
        },
        .category    = "bench/dirtyrect",
    });
    registry.add(Desc{
        .id          = "BenchB09_LongForm10Minutes",
        .factory     = [](const chronon3d::CompositionProps&) {
            return bench_b09_long_form_10_minutes();
        },
        .category    = "bench/stability",
    });
    registry.add(Desc{
        .id          = "BenchB10_RandomFrameAccess",
        .factory     = [](const chronon3d::CompositionProps&) {
            return bench_b10_random_frame_access();
        },
        .category    = "bench/cache",
    });
    registry.add(Desc{
        .id          = "BenchB11_Portrait1080x1920",
        .factory     = [](const chronon3d::CompositionProps&) {
            return bench_b11_portrait_1080x1920();
        },
        .category    = "bench/portrait",
    });

    // ── B07 inner precomps — registered so outer composition's precomp()
    // references resolve at evaluation time. These are NOT part of the
    // canonical 12-scene corpus; they are composition-graph dependencies.
    registry.add(Desc{
        .id          = "BenchB07InnerA",
        .factory     = [](const chronon3d::CompositionProps&) {
            return bench_b07_inner::inner_a();
        },
        .category    = "bench/internal",
    });
    registry.add(Desc{
        .id          = "BenchB07InnerB",
        .factory     = [](const chronon3d::CompositionProps&) {
            return bench_b07_inner::inner_b();
        },
        .category    = "bench/internal",
    });
    registry.add(Desc{
        .id          = "BenchB07InnerC",
        .factory     = [](const chronon3d::CompositionProps&) {
            return bench_b07_inner::inner_c();
        },
        .category    = "bench/internal",
    });
}

} // namespace chronon3d::bench_corpus
