// ${PROJECT_NAME} — HelloWorld composition (generated by `chronon create`)
//
// Defines the canonical "HelloWorld" composition using the SceneBuilder
// facade.  Edit this file to add layers, animations, sequences, etc.
//
// Canonical facade: authoring::Scene / authoring::Layer.
// Do NOT use the legacy LayerBuilder::text(name, TextSpec) overload or
// process-wide asset paths; both are deprecated in V0.1.

#include <chronon3d/api/composition.hpp>
#include <chronon3d/api/scene.hpp>
#include <chronon3d/scene/builders/scene_builder.hpp>
#include <chronon3d/scene/builders/layer_builder.hpp>
#include <chronon3d/core/types/frame.hpp>
#include <chronon3d/core/types/frame_context.hpp>
#include <chronon3d/project.hpp>
#include <chronon3d/text/text_definition.hpp>

namespace c3d = chronon3d;

void make_hello_world(c3d::Project& project) {
    project.composition("HelloWorld", {.duration = c3d::Frame{1}},
        [](const c3d::FrameContext& ctx) -> c3d::Scene {
            c3d::SceneBuilder s(ctx);
            if (ctx.runtime && ctx.runtime->font_engine()) {
                s.font_engine(ctx.runtime->font_engine());
            }

            // Background layer — solid color fill.
            s.layer("bg", [](c3d::LayerBuilder& l) {
                l.fill(c3d::Color{0.1f, 0.1f, 0.15f, 1.0f});
            });

            // Title layer — centered text using the canonical Text fluent API.
            s.layer("title", [&ctx](c3d::LayerBuilder& l) {
                l.font("fonts/Inter-Bold.ttf")
                 .font_size(72.0f)
                 .center();
                l.animated_text("t", c3d::TextRunSpec{
                    .text = c3d::TextDefinition{
                        .content = {.value = "Hello, World!"},
                        .style = {
                            .font = {.font_family = "Inter", .font_weight = 700},
                            .color = c3d::Color::white()
                        },
                        .frame = {
                            .size = {static_cast<float>(ctx.width),
                                     static_cast<float>(ctx.height)}
                        }
                    }
                }).commit();
            });

            return s.build();
        });
}
