// ${PROJECT_NAME} — Chronon3D project (generated by `chronon create`)
//
// Standalone binary: registers the "HelloWorld" composition and renders
// it directly via the canonical sdk::RenderEngine.  The result is
// printed to stdout; see README.md → "Adding PNG output" to write
// the framebuffer to a PNG file.
//
// Build & run:
//   cmake -B build
//   cmake --build build
//   ./build/${PROJECT_NAME}

#include <chronon3d/sdk/render_settings.hpp>
#include <chronon3d/sdk/render_engine.hpp>
#include <chronon3d/api/composition.hpp>
#include <chronon3d/api/scene.hpp>
#include <chronon3d/scene/builders/scene_builder.hpp>
#include <chronon3d/scene/builders/layer_builder.hpp>
#include <chronon3d/core/types/frame.hpp>
#include <chronon3d/core/types/frame_context.hpp>
#include <chronon3d/project.hpp>
#include <chronon3d/text/text_definition.hpp>

#include <cstdio>

namespace c3d = chronon3d;

// Forward-declared in hello_world.cpp — registers the "HelloWorld"
// composition into the project.  Edit hello_world.cpp to customize.
void make_hello_world(c3d::Project& project);

int main() {
    // 1. Project — single entry point (Remotion's registerRoot() equivalent).
    c3d::Project project;
    project.name           = "${PROJECT_NAME}";
    project.default_width  = 1280;
    project.default_height = 720;
    project.assets_root    = "assets";

    // 2. Register the "HelloWorld" composition.
    make_hello_world(project);

    // 3. Render — SDK engine, deterministic, single-frame.
    c3d::sdk::RenderSettings settings{
        .width = 1280,
        .height = 720,
        .deterministic = true
    };
    c3d::sdk::RenderEngine engine{settings};
    engine.set_assets_root("assets");

    auto result = engine.render(project.create("HelloWorld"), c3d::sdk::Frame{0});
    if (!result) {
        std::fprintf(stderr, "Render failed: %s\n", result.error().message.c_str());
        return 1;
    }

    std::printf("✓ Rendered \"%s\" (%dx%d) — %zu compositions registered\n",
                project.name.c_str(), result->width, result->height, project.size());
    return 0;
}
