// ---------------------------------------------------------------------------
// tools/shaders/spirv_abi_gen.cpp
//
// Host build-time tool: reads a compiled SPIR-V .spv file and generates a
// C++ header with typed ABI constants (descriptor bindings, push constant
// size, local workgroup size).  Linked against spirv-reflect.
//
// Usage: spirv_abi_gen <input.spv> <output.hpp> <struct_prefix>
// Example: spirv_abi_gen text_batch.comp.spv gen/text_batch_abi.hpp TextBatch
// ---------------------------------------------------------------------------

#include <spirv_reflect.h>

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

static std::string read_spv(const char* path) {
    std::ifstream in(path, std::ios::binary | std::ios::ate);
    if (!in) {
        std::cerr << "spirv_abi_gen: cannot open " << path << '\n';
        std::exit(1);
    }
    const auto size = static_cast<std::size_t>(in.tellg());
    in.seekg(0);
    std::string buf(size, '\0');
    if (!in.read(buf.data(), static_cast<std::streamsize>(size))) {
        std::cerr << "spirv_abi_gen: read error " << path << '\n';
        std::exit(1);
    }
    return buf;
}

static void write_header(std::ostream& out,
                         const std::string& prefix,
                         const SpvReflectShaderModule& module) {
    // A compute shader always declares exactly one entry point; the local
    // workgroup size lives on that entry point (not the module).
    const SpvReflectEntryPoint& ep = module.entry_points[0];

    out << "// Auto-generated by tools/shaders/spirv_abi_gen.cpp — do not edit\n"
        << "// Source shader entry point: " << module.entry_point_name << "\n"
        << "#pragma once\n\n"
        << "#include <cstddef>\n"
        << "#include <cstdint>\n\n"
        << "namespace chronon3d::backends::vulkan::shaders {\n\n"
        << "struct " << prefix << "ShaderAbi {\n";

    out << "    // Workgroup local size (from entry point \"" << ep.name << "\")\n"
        << "    static constexpr std::uint32_t kLocalSizeX = " << ep.local_size.x << ";\n"
        << "    static constexpr std::uint32_t kLocalSizeY = " << ep.local_size.y << ";\n"
        << "    static constexpr std::uint32_t kLocalSizeZ = " << ep.local_size.z << ";\n\n";

    // Descriptor bindings
    std::uint32_t binding_count = 0;
    spvReflectEnumerateDescriptorBindings(&module, &binding_count, nullptr);
    std::vector<SpvReflectDescriptorBinding*> bindings(binding_count);
    spvReflectEnumerateDescriptorBindings(&module, &binding_count, bindings.data());

    if (binding_count > 0) {
        out << "    // Descriptor bindings\n";
        for (const auto* b : bindings) {
            const char* type_str = "unknown";
            switch (b->descriptor_type) {
                case SPV_REFLECT_DESCRIPTOR_TYPE_STORAGE_IMAGE:   type_str = "StorageImage"; break;
                case SPV_REFLECT_DESCRIPTOR_TYPE_STORAGE_BUFFER:  type_str = "StorageBuffer"; break;
                case SPV_REFLECT_DESCRIPTOR_TYPE_UNIFORM_BUFFER:  type_str = "UniformBuffer"; break;
                case SPV_REFLECT_DESCRIPTOR_TYPE_SAMPLER:         type_str = "Sampler"; break;
                case SPV_REFLECT_DESCRIPTOR_TYPE_SAMPLED_IMAGE:   type_str = "SampledImage"; break;
                case SPV_REFLECT_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER: type_str = "CombinedImageSampler"; break;
                default: break;
            }
            out << "    static constexpr std::uint32_t kSet" << b->set
                << "Binding" << b->binding << " = " << b->binding
                << ";  // " << b->name << " (" << type_str << ")\n";
        }
        out << "\n";
    }

    // Push constant blocks
    std::uint32_t push_count = 0;
    spvReflectEnumeratePushConstantBlocks(&module, &push_count, nullptr);
    std::vector<SpvReflectBlockVariable*> push_constants(push_count);
    spvReflectEnumeratePushConstantBlocks(&module, &push_count, push_constants.data());

    if (push_count > 0) {
        out << "    // Push constant blocks\n";
        for (const auto* pc : push_constants) {
            out << "    static constexpr std::uint32_t kPushConstantSize = " << pc->size << ";\n";
        }
        out << "\n";
    }

    out << "};  // " << prefix << "ShaderAbi\n\n"
        << "}  // namespace chronon3d::backends::vulkan::shaders\n";
}

int main(int argc, char* argv[]) {
    if (argc != 4) {
        std::cerr << "Usage: spirv_abi_gen <input.spv> <output.hpp> <struct_prefix>\n";
        return 1;
    }

    const char* input_path  = argv[1];
    const char* output_path = argv[2];
    const std::string prefix = argv[3];

    const std::string spv_data = read_spv(input_path);

    SpvReflectShaderModule module{};
    const SpvReflectResult result = spvReflectCreateShaderModule(
        spv_data.size(), spv_data.data(), &module);
    if (result != SPV_REFLECT_RESULT_SUCCESS) {
        std::cerr << "spirv_abi_gen: spvReflectCreateShaderModule failed for " << input_path << '\n';
        return 1;
    }
    if (module.entry_point_count == 0 || module.entry_points == nullptr) {
        std::cerr << "spirv_abi_gen: no entry point found in " << input_path << '\n';
        spvReflectDestroyShaderModule(&module);
        return 1;
    }

    std::ofstream out(output_path);
    if (!out) {
        std::cerr << "spirv_abi_gen: cannot write " << output_path << '\n';
        spvReflectDestroyShaderModule(&module);
        return 1;
    }

    write_header(out, prefix, module);

    spvReflectDestroyShaderModule(&module);
    return 0;
}