// ---------------------------------------------------------------------------// overlay_hud_panels.cpp — Safe area, target crosshair, bounds, null/parent markers// Extracted from camera_debug_overlay.cpp// ---------------------------------------------------------------------------#include"camera_debug_overlay_panels.hpp"#include<algorithm>namespacechronon3d{voiddraw_safe_area_and_target(constOverlayContext&ctx,bool&has_target,ScreenPoint&sp,Color&target_color){auto&l=ctx.layer;boolsafe_area_failed=false;for(constauto&f:ctx.report.failures){if(f.find("safe area")!=std::string::npos||f.find("outside safe")!=std::string::npos){safe_area_failed=true;break;}}Colorsafe_area_color=safe_area_failed?Color{1.0f,0.2f,0.2f,0.7f}:Color{0.2f,0.9f,0.2f,0.5f};if(ctx.options.show_safe_area){l.rect("safe_area_hud",RectParams{.size={ctx.viewport.width*0.90f,ctx.viewport.height*0.90f},.pos={ctx.viewport.width*0.05f,ctx.viewport.height*0.05f,0.0f},.fill=FillStyle{.enabled=false},.stroke={.enabled=true,.color=safe_area_color,.width=1.5f}});}Vec3target_world{0.0f,0.0f,0.0f};has_target=false;if(!ctx.camera.target_name.empty()){autopos_opt=ctx.resolved.world_position(std::string(ctx.camera.target_name));if(pos_opt){target_world=*pos_opt;has_target=true;}}elseif(ctx.camera.point_of_interest_enabled){target_world=ctx.camera.point_of_interest;has_target=true;}if(has_target){sp=project_world_to_screen(target_world,ctx.camera,ctx.viewport);}target_color=Color{0.2f,0.9f,0.2f,0.8f};if(ctx.report.target_center_error_px>3.0f){target_color=Color{1.0f,0.2f,0.2f,0.8f};}elseif(ctx.report.target_center_error_px>1.5f){target_color=Color{1.0f,0.8f,0.0f,0.8f};}if(ctx.options.show_target){Vec2center=has_target&&!sp.behind_camera?sp.position:Vec2{ctx.viewport.width*0.5f,ctx.viewport.height*0.5f};l.line("target_cross_h",LineParams{.from={center.x-25.0f,center.y,0.0f},.to={center.x+25.0f,center.y,0.0f},.thickness=2.0f,.color=target_color});l.line("target_cross_v",LineParams{.from={center.x,center.y-25.0f,0.0f},.to={center.x,center.y+25.0f,0.0f},.thickness=2.0f,.color=target_color});l.circle("target_cross_dot",CircleParams{.radius=4.0f,.color=target_color,.pos={center.x,center.y,0.0f}});}}voiddraw_camera_to_target_line(constOverlayContext&ctx,constScreenPoint&sp,boolhas_target,constColor&target_color){auto&l=ctx.layer;if(!ctx.options.show_camera_to_target_line||!has_target||sp.behind_camera)return;l.line("camera_to_target_line",LineParams{.from={ctx.viewport.width*0.5f,ctx.viewport.height*0.5f,0.0f},.to={sp.position.x,sp.position.y,0.0f},.thickness=1.5f,.color=target_color});floatdist=glm::distance(sp.position,Vec2{ctx.viewport.width*0.5f,ctx.viewport.height*0.5f});if(dist>1.0f){l.text("target_deviation_text",TextSpec{
    .content = {.value = std::to_string(static_cast<int>(dist)) + "px error"},
    .font = {.font_size = 12.0f},
    .appearance = {.color = target_color},
    .position = {(ctx.viewport.width * 0.5f + sp.position.x) * 0.5f + 10.0f,
                    (ctx.viewport.height * 0.5f + sp.position.y) * 0.5f + 10.0f, 0.0f}
});}}voiddraw_null_parent_markers(constOverlayContext&ctx){auto&l=ctx.layer;for(constauto&pair:ctx.resolved.resolved){conststd::string&name=pair.first;if(name.find("_null")!=std::string::npos||name.find("_parent")!=std::string::npos){Vec3null_pos=Vec3(pair.second.world_matrix[3]);ScreenPointn_sp=project_world_to_screen(null_pos,ctx.camera,ctx.viewport);if(!n_sp.behind_camera){l.rect("null_parent_rect_"+name,RectParams{.size={12.0f,12.0f},.pos={n_sp.position.x-6.0f,n_sp.position.y-6.0f,0.0f},.fill=FillStyle{.enabled=false},.stroke={.enabled=true,.color=Color{0.0f,0.9f,1.0f,0.8f},.width=1.5f}});l.line("null_parent_h_"+name,LineParams{.from={n_sp.position.x-12.0f,n_sp.position.y,0.0f},.to={n_sp.position.x+12.0f,n_sp.position.y,0.0f},.thickness=1.0f,.color=Color{0.0f,0.9f,1.0f,0.8f}});l.line("null_parent_v_"+name,LineParams{.from={n_sp.position.x,n_sp.position.y-12.0f,0.0f},.to={n_sp.position.x,n_sp.position.y+12.0f,0.0f},.thickness=1.0f,.color=Color{0.0f,0.9f,1.0f,0.8f}});l.text("null_parent_lbl_"+name,TextSpec{
    .content = {.value = name},
    .font = {.font_size = 10.0f},
    .appearance = {.color = Color{0.0f, 0.9f, 1.0f, 0.8f}},
    .position = {n_sp.position.x + 15.0f, n_sp.position.y + 5.0f, 0.0f}
});}}}}voiddraw_parent_child_links(constOverlayContext&ctx){auto&l=ctx.layer;for(constauto&pair:ctx.resolved.resolved){conststd::string&child_name=pair.first;constResolvedTransform3D&r3d=pair.second;if(!r3d.local.parent_name.empty()){autoparent_pos_opt=ctx.resolved.world_position(r3d.local.parent_name);autochild_pos_opt=ctx.resolved.world_position(child_name);if(parent_pos_opt&&child_pos_opt){ScreenPointparent_sp=project_world_to_screen(*parent_pos_opt,ctx.camera,ctx.viewport);ScreenPointchild_sp=project_world_to_screen(*child_pos_opt,ctx.camera,ctx.viewport);if(!parent_sp.behind_camera&&!child_sp.behind_camera){l.line("link_"+r3d.local.parent_name+"_"+child_name,LineParams{.from={parent_sp.position.x,parent_sp.position.y,0.0f},.to={child_sp.position.x,child_sp.position.y,0.0f},.thickness=1.0f,.color=Color{0.0f,0.7f,1.0f,0.4f}});}}}}}voiddraw_projected_bounds(constOverlayContext&ctx){auto&l=ctx.layer;if(!ctx.options.show_projected_bounds)return;intidx=0;for(constauto&lr:ctx.report.layers){Colorborder_color=lr.passed?Color{0.2f,0.9f,0.2f,0.6f}:Color{1.0f,0.2f,0.2f,0.8f};if(ctx.report.composition_name=="CameraFrustumCullingPrecisionTest"){border_color=lr.bounds.visible_ratio>0.0f?Color{0.2f,0.9f,0.2f,0.6f}:Color{0.5f,0.5f,0.5f,0.15f};}Vec2b_size=lr.bounds.max-lr.bounds.min;if(b_size.x>0.0f&&b_size.y>0.0f){std::stringnode_name="bounds_hud_"+lr.name+"_"+std::to_string(idx);l.rect(node_name,RectParams{.size=b_size,.pos={lr.bounds.min.x,lr.bounds.min.y,0.0f},.fill=FillStyle{.enabled=false},.stroke={.enabled=true,.color=border_color,.width=1.5f}});if(ctx.options.show_layer_names){l.text("label_hud_"+lr.name+"_"+std::to_string(idx),TextSpec{
    .content = {.value = lr.name + (lr.passed ? " (PASS)" : " (FAIL)")},
    .font = {.font_size = 12.0f},
    .appearance = {.color = border_color},
    .position = {lr.bounds.min.x + 5.0f, lr.bounds.min.y + 15.0f, 0.0f}
});}}idx++;}}}// namespace chronon3d