# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chronon3d_pb2 as chronon3d__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chronon3d_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChrononServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCompositions = channel.unary_unary(
                '/chronon3d.ChrononService/ListCompositions',
                request_serializer=chronon3d__pb2.ListCompositionsRequest.SerializeToString,
                response_deserializer=chronon3d__pb2.ListCompositionsResponse.FromString,
                _registered_method=True)
        self.RenderVideo = channel.unary_stream(
                '/chronon3d.ChrononService/RenderVideo',
                request_serializer=chronon3d__pb2.RenderVideoRequest.SerializeToString,
                response_deserializer=chronon3d__pb2.RenderVideoProgress.FromString,
                _registered_method=True)
        self.RenderFrame = channel.unary_unary(
                '/chronon3d.ChrononService/RenderFrame',
                request_serializer=chronon3d__pb2.RenderFrameRequest.SerializeToString,
                response_deserializer=chronon3d__pb2.RenderFrameResponse.FromString,
                _registered_method=True)
        self.GetSystemStatus = channel.unary_unary(
                '/chronon3d.ChrononService/GetSystemStatus',
                request_serializer=chronon3d__pb2.SystemStatusRequest.SerializeToString,
                response_deserializer=chronon3d__pb2.SystemStatusResponse.FromString,
                _registered_method=True)


class ChrononServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListCompositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenderVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenderFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChrononServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListCompositions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCompositions,
                    request_deserializer=chronon3d__pb2.ListCompositionsRequest.FromString,
                    response_serializer=chronon3d__pb2.ListCompositionsResponse.SerializeToString,
            ),
            'RenderVideo': grpc.unary_stream_rpc_method_handler(
                    servicer.RenderVideo,
                    request_deserializer=chronon3d__pb2.RenderVideoRequest.FromString,
                    response_serializer=chronon3d__pb2.RenderVideoProgress.SerializeToString,
            ),
            'RenderFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.RenderFrame,
                    request_deserializer=chronon3d__pb2.RenderFrameRequest.FromString,
                    response_serializer=chronon3d__pb2.RenderFrameResponse.SerializeToString,
            ),
            'GetSystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStatus,
                    request_deserializer=chronon3d__pb2.SystemStatusRequest.FromString,
                    response_serializer=chronon3d__pb2.SystemStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chronon3d.ChrononService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chronon3d.ChrononService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChrononService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListCompositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronon3d.ChrononService/ListCompositions',
            chronon3d__pb2.ListCompositionsRequest.SerializeToString,
            chronon3d__pb2.ListCompositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenderVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chronon3d.ChrononService/RenderVideo',
            chronon3d__pb2.RenderVideoRequest.SerializeToString,
            chronon3d__pb2.RenderVideoProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenderFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronon3d.ChrononService/RenderFrame',
            chronon3d__pb2.RenderFrameRequest.SerializeToString,
            chronon3d__pb2.RenderFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronon3d.ChrononService/GetSystemStatus',
            chronon3d__pb2.SystemStatusRequest.SerializeToString,
            chronon3d__pb2.SystemStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
