#include <chronon3d/core/builtin_compositions.hpp>

namespace chronon3d {

#if defined(CHRONON3D_BUILD_EXAMPLES)
extern Composition AdvancedVideo();
extern Composition AnimatedBlurRevealProof();
extern Composition AnimatedImageProof();
extern Composition AnimatedLayerProof();
extern Composition AnimatedMaskRevealProof();
extern Composition AnimatedTitleCard();
extern Composition AnimatedVisualQualityProof();
extern Composition AxisDebug();
extern Composition BasicShapes();
extern Composition BlendingShowcase();
extern Composition BlendModeProof();
extern Composition BloomProof();
extern Composition BlurProof();
extern Composition BrightnessContrastProof();
extern Composition camera25d_graph_2d_overlay();
extern Composition camera25d_graph_culling();
extern Composition camera25d_graph_dof();
extern Composition camera25d_graph_parallax();
extern Composition camera25d_graph_projection();
extern Composition camera25d_graph_pushin();
extern Composition camera25d_graph_scena();
extern Composition camera25d_graph_z_sorting();
extern Composition Camera25DCameraPushProof();
extern Composition Camera25DDepthScaleProof();
extern Composition Camera25DImageParallaxProof();
extern Composition Camera25DMixed2D3DProof();
extern Composition Camera25DParallaxProof();
extern Composition Camera25DZOrderProof();
extern Composition CameraAxisDebugProof();
extern Composition CameraBasicTwoNodeProof();
extern Composition CameraFallbackProof();
extern Composition CameraLookAtProof();
extern Composition CameraOrbitProof();
extern Composition CameraParallaxProof();
extern Composition CameraTargetOrbitProof();
extern Composition CameraZoomComparisonProof();
extern Composition CheckerGen();
extern Composition CodeFirstSmoke();
extern Composition ContactShadowProof();
extern Composition DebugProjection();
extern Composition DepthOffsetProof();
extern Composition DepthRoleOffsetProof();
extern Composition DepthRolesProof();
extern Composition Fake3DStudioProof();
extern Composition FakeBox3DProof();
extern Composition FakeExtrudedTextProof();
extern Composition First2_5DShot();
extern Composition First2_5DShotFov();
extern Composition FoundationProof();
extern Composition GlowProof();
extern Composition GridPlaneProof();
extern Composition ImageAlphaProof();
extern Composition ImageClippingProof();
extern Composition ImageDrawOrderProof();
extern Composition ImageLayerTransformProof();
extern Composition ImageMissingProof();
extern Composition ImageProof();
extern Composition KeyframesProof();
extern Composition LayerChildDrawOrderProof();
extern Composition LayerDrawOrderProof();
extern Composition LayerLocalCoordinatesProof();
extern Composition LayerOpacityProof();
extern Composition LayerProof();
extern Composition LayerTransformStressProof();
extern Composition LayerVisibilityProof();
extern Composition MaskCamera25DProof();
extern Composition MaskCircleProof();
extern Composition MaskLayerTransformProof();
extern Composition MaskRectProof();
extern Composition MaskRoundedRectProof();
extern Composition MaskTextRevealProof();
extern Composition MovingRect();
extern Composition ParallaxRolesProof();
extern Composition ParentingRigProof();
extern Composition PremiumLookProof();
extern Composition ProjectedPlaneValidation();
extern Composition RoundedRectProof();
extern Composition ShadowProof();
extern Composition Text3DDepthStressTest();
extern Composition Text3DOrientationTest();
extern Composition Text3DWindingTest();
extern Composition TextAlignProof();
extern Composition TextAlphaProof();
extern Composition TextClippingProof();
extern Composition TextDrawOrderProof();
extern Composition TextGlyph01_BaselineAscendersDescenders();
extern Composition TextGlyph02_KerningPairs();
extern Composition TextGlyph03_GlyphCoverageAccentsSymbols();
extern Composition TextGlyph04_MultilineWrapAlignment();
extern Composition TextGlyph05_StrokeShadowGlowReadability();
extern Composition TextGlyph06_AlphaBlendingTextOpacity();
extern Composition TextGlyph07_PositioningFractionalPixels();
extern Composition TextGlyph08_MixedScriptsFallback();
extern Composition TextMissingFontProof();
extern Composition TextProof();
extern Composition TextSizesProof();
extern Composition TintProof();
extern Composition TmplLowerThird();
extern Composition TmplStudioBlue();
extern Composition TmplStudioOrange();
extern Composition TodayFirst25D();
extern Composition TopViewDebugProof();
extern Composition TransformProof();
extern Composition VisualStackOrderProof();
extern Composition VisualTest_Easing();
extern Composition VisualTest_Glass();
extern Composition VisualTest_Reflection();
extern Composition VisualTest_SSAA();
extern Composition VisualTest_Wiggle();
extern Composition ZSortingProof();

void register_builtin_compositions(CompositionRegistry& registry) {
    registry.add("AdvancedShowcase", AdvancedVideo);
    registry.add("AnimatedBlurRevealProof", AnimatedBlurRevealProof);
    registry.add("AnimatedImageProof", AnimatedImageProof);
    registry.add("AnimatedLayerProof", AnimatedLayerProof);
    registry.add("AnimatedMaskRevealProof", AnimatedMaskRevealProof);
    registry.add("AnimatedTitleCard", AnimatedTitleCard);
    registry.add("AnimatedVisualQualityProof", AnimatedVisualQualityProof);
    registry.add("AxisDebug", AxisDebug);
    registry.add("BasicShapes", BasicShapes);
    registry.add("BlendingShowcase", BlendingShowcase);
    registry.add("BlendModeProof", BlendModeProof);
    registry.add("BloomProof", BloomProof);
    registry.add("BlurProof", BlurProof);
    registry.add("BrightnessContrastProof", BrightnessContrastProof);
    registry.add("camera25d_graph_2d_overlay", camera25d_graph_2d_overlay);
    registry.add("camera25d_graph_culling", camera25d_graph_culling);
    registry.add("camera25d_graph_dof", camera25d_graph_dof);
    registry.add("camera25d_graph_parallax", camera25d_graph_parallax);
    registry.add("camera25d_graph_projection", camera25d_graph_projection);
    registry.add("camera25d_graph_pushin", camera25d_graph_pushin);
    registry.add("camera25d_graph_scena", camera25d_graph_scena);
    registry.add("camera25d_graph_z_sorting", camera25d_graph_z_sorting);
    registry.add("Camera25DCameraPushProof", Camera25DCameraPushProof);
    registry.add("Camera25DDepthScaleProof", Camera25DDepthScaleProof);
    registry.add("Camera25DImageParallaxProof", Camera25DImageParallaxProof);
    registry.add("Camera25DMixed2D3DProof", Camera25DMixed2D3DProof);
    registry.add("Camera25DParallaxProof", Camera25DParallaxProof);
    registry.add("Camera25DZOrderProof", Camera25DZOrderProof);
    registry.add("CameraAxisDebugProof", CameraAxisDebugProof);
    registry.add("CameraBasicTwoNodeProof", CameraBasicTwoNodeProof);
    registry.add("CameraFallbackProof", CameraFallbackProof);
    registry.add("CameraLookAtProof", CameraLookAtProof);
    registry.add("CameraOrbitProof", CameraOrbitProof);
    registry.add("CameraParallaxProof", CameraParallaxProof);
    registry.add("CameraTargetOrbitProof", CameraTargetOrbitProof);
    registry.add("CameraZoomComparisonProof", CameraZoomComparisonProof);
    registry.add("CheckerGen", CheckerGen);
    registry.add("CodeFirstSmoke", CodeFirstSmoke);
    registry.add("ContactShadowProof", ContactShadowProof);
    registry.add("DebugProjection", DebugProjection);
    registry.add("DepthOffsetProof", DepthOffsetProof);
    registry.add("DepthRoleOffsetProof", DepthRoleOffsetProof);
    registry.add("DepthRolesProof", DepthRolesProof);
    registry.add("Fake3DStudioProof", Fake3DStudioProof);
    registry.add("FakeBox3DProof", FakeBox3DProof);
    registry.add("FakeExtrudedTextProof", FakeExtrudedTextProof);
    registry.add("First2_5DShot", First2_5DShot);
    registry.add("First2_5DShotFov", First2_5DShotFov);
    registry.add("FoundationProof", FoundationProof);
    registry.add("GlowProof", GlowProof);
    registry.add("GridPlaneProof", GridPlaneProof);
    registry.add("ImageAlphaProof", ImageAlphaProof);
    registry.add("ImageClippingProof", ImageClippingProof);
    registry.add("ImageDrawOrderProof", ImageDrawOrderProof);
    registry.add("ImageLayerTransformProof", ImageLayerTransformProof);
    registry.add("ImageMissingProof", ImageMissingProof);
    registry.add("ImageProof", ImageProof);
    registry.add("KeyframesProof", KeyframesProof);
    registry.add("LayerChildDrawOrderProof", LayerChildDrawOrderProof);
    registry.add("LayerDrawOrderProof", LayerDrawOrderProof);
    registry.add("LayerLocalCoordinatesProof", LayerLocalCoordinatesProof);
    registry.add("LayerOpacityProof", LayerOpacityProof);
    registry.add("LayerProof", LayerProof);
    registry.add("LayerTransformStressProof", LayerTransformStressProof);
    registry.add("LayerVisibilityProof", LayerVisibilityProof);
    registry.add("MaskCamera25DProof", MaskCamera25DProof);
    registry.add("MaskCircleProof", MaskCircleProof);
    registry.add("MaskLayerTransformProof", MaskLayerTransformProof);
    registry.add("MaskRectProof", MaskRectProof);
    registry.add("MaskRoundedRectProof", MaskRoundedRectProof);
    registry.add("MaskTextRevealProof", MaskTextRevealProof);
    registry.add("MovingRect", MovingRect);
    registry.add("ParallaxRolesProof", ParallaxRolesProof);
    registry.add("ParentingRigProof", ParentingRigProof);
    registry.add("PremiumLookProof", PremiumLookProof);
    registry.add("ProjectedPlaneValidation", ProjectedPlaneValidation);
    registry.add("RoundedRectProof", RoundedRectProof);
    registry.add("ShadowProof", ShadowProof);
    registry.add("Text3DDepthStressTest", Text3DDepthStressTest);
    registry.add("Text3DOrientationTest", Text3DOrientationTest);
    registry.add("Text3DWindingTest", Text3DWindingTest);
    registry.add("TextAlignProof", TextAlignProof);
    registry.add("TextAlphaProof", TextAlphaProof);
    registry.add("TextClippingProof", TextClippingProof);
    registry.add("TextDrawOrderProof", TextDrawOrderProof);
    registry.add("TextGlyph01_BaselineAscendersDescenders", TextGlyph01_BaselineAscendersDescenders);
    registry.add("TextGlyph02_KerningPairs", TextGlyph02_KerningPairs);
    registry.add("TextGlyph03_GlyphCoverageAccentsSymbols", TextGlyph03_GlyphCoverageAccentsSymbols);
    registry.add("TextGlyph04_MultilineWrapAlignment", TextGlyph04_MultilineWrapAlignment);
    registry.add("TextGlyph05_StrokeShadowGlowReadability", TextGlyph05_StrokeShadowGlowReadability);
    registry.add("TextGlyph06_AlphaBlendingTextOpacity", TextGlyph06_AlphaBlendingTextOpacity);
    registry.add("TextGlyph07_PositioningFractionalPixels", TextGlyph07_PositioningFractionalPixels);
    registry.add("TextGlyph08_MixedScriptsFallback", TextGlyph08_MixedScriptsFallback);
    registry.add("TextMissingFontProof", TextMissingFontProof);
    registry.add("TextProof", TextProof);
    registry.add("TextSizesProof", TextSizesProof);
    registry.add("TintProof", TintProof);
    registry.add("TmplLowerThird", TmplLowerThird);
    registry.add("TmplStudioBlue", TmplStudioBlue);
    registry.add("TmplStudioOrange", TmplStudioOrange);
    registry.add("TodayFirst25D", TodayFirst25D);
    registry.add("TopViewDebugProof", TopViewDebugProof);
    registry.add("TransformProof", TransformProof);
    registry.add("VisualStackOrderProof", VisualStackOrderProof);
    registry.add("VisualTest_Easing", VisualTest_Easing);
    registry.add("VisualTest_Glass", VisualTest_Glass);
    registry.add("VisualTest_Reflection", VisualTest_Reflection);
    registry.add("VisualTest_SSAA", VisualTest_SSAA);
    registry.add("VisualTest_Wiggle", VisualTest_Wiggle);
    registry.add("ZSortingProof", ZSortingProof);
}
#else
void register_builtin_compositions(CompositionRegistry&) {}
#endif

} // namespace chronon3d