#!/usr/bin/env bash
# ═════════════════════════════════════════════════════════════════════════════
# tools/build_sdk_bundle.sh
#
# Wraps a self-describing SDK stage install into the single distributable
# product bundle:
#
#     chronon-sdk-<platform>/
#     ├── bin/              (chronon3d_cli — only when built/installed)
#     ├── include/          (public + authoring headers, C ABI header)
#     ├── lib/              (libchronon3d_c.so{,.2,.<version>},
#     │                       libchronon3d_sdk_impl.a, pkgconfig/, cmake/Chronon3D/)
#     ├── share/            (RenderPlan schema + presets)
#     ├── VERSION           (single-line package version)
#     └── manifest.json     (SDK PACKAGE MANIFEST, not the render receipt)
#
# plus its tarball:
#
#     chronon-sdk-<platform>.tar.gz
#
# The stage is the product.  `cmake --install --prefix <stage>` already emits
# bin/include/lib/share plus VERSION and manifest.json (generated by
# cmake/Chronon3DSdkInstall.cmake — the single source of truth for their
# content).  This script is a thin wrapper: it copies the stage into the
# platform-named top-level directory and tars it.  It does NOT regenerate
# VERSION/manifest.json, so the bundle can never drift from the installed
# package.
#
# Environment:
#   SDK_PREFIX             (required) stage install dir (cmake --install --prefix)
#   SDK_BUNDLE_OUT         output dir for the bundle + tarball (default: $PWD)
#   CHRONON3D_BUNDLE_KEEP=1  keep the bundle directory after creating the tarball
#
# Exit codes:
#   0 = CHRONON_SDK_BUNDLE_PASS
#   1 = bundle FAILED (missing stage artifacts / copy or tar error)
#
# Invocation:
#   cmake --install build-release --prefix "$PWD/stage/chronon"
#   SDK_PREFIX="$PWD/stage/chronon" bash tools/build_sdk_bundle.sh
# ═════════════════════════════════════════════════════════════════════════════
set -euo pipefail

log()  { printf '[build_sdk_bundle] %s\n' "$*" >&2; }
fail() { log "FAIL: $*"; exit 1; }

: "${SDK_PREFIX:?SDK_PREFIX env var required (the cmake --install --prefix stage)}"
SDK_BUNDLE_OUT="${SDK_BUNDLE_OUT:-$PWD}"
KEEP="${CHRONON3D_BUNDLE_KEEP:-0}"

# ── Platform (bundle directory NAME only; manifest content lives in CMake) ─
os="$(uname -s | tr '[:upper:]' '[:lower:]')"
arch="$(uname -m | tr '[:upper:]' '[:lower:]')"
platform="${os}-${arch}"
bundle_name="chronon-sdk-${platform}"

# ── The stage must be a complete self-describing product ────────────────────
[[ -e "$SDK_PREFIX/lib/libchronon3d_c.so" ]] \
    || fail "staged libchronon3d_c.so missing in $SDK_PREFIX"
[[ -f "$SDK_PREFIX/include/chronon3d/c_api/chronon3d.h" ]] \
    || fail "staged C ABI header missing in $SDK_PREFIX"
[[ -f "$SDK_PREFIX/lib/cmake/Chronon3D/Chronon3DConfig.cmake" ]] \
    || fail "staged Chronon3DConfig.cmake missing in $SDK_PREFIX"
[[ -f "$SDK_PREFIX/VERSION" && -s "$SDK_PREFIX/VERSION" ]] \
    || fail "staged VERSION missing/empty (re-run cmake --install; cmake/Chronon3DSdkInstall.cmake installs it)"
[[ -f "$SDK_PREFIX/manifest.json" && -s "$SDK_PREFIX/manifest.json" ]] \
    || fail "staged manifest.json missing/empty (re-run cmake --install; cmake/Chronon3DSdkInstall.cmake installs it)"

# ── Assemble the bundle (copy the stage verbatim) ───────────────────────────
mkdir -p "$SDK_BUNDLE_OUT"
bundle_dir="$SDK_BUNDLE_OUT/$bundle_name"
rm -rf "$bundle_dir"
mkdir -p "$bundle_dir"

log "assembling $bundle_name from $SDK_PREFIX"
for entry in bin include lib share VERSION manifest.json; do
    [[ -e "$SDK_PREFIX/$entry" ]] && cp -a "$SDK_PREFIX/$entry" "$bundle_dir/"
done

# ── Package the bundle ──────────────────────────────────────────────────────
tarball="$SDK_BUNDLE_OUT/$bundle_name.tar.gz"
log "creating $tarball"
tar -czf "$tarball" -C "$SDK_BUNDLE_OUT" "$bundle_name" || fail "tar create failed"

# Sanity: the tarball must carry the documented top-level layout.  Capture the
# listing once and grep a here-string (not a pipe): piping into `grep -q`
# would early-exit on the first match and SIGPIPE `tar`, which under
# `set -o pipefail` turns a present member into a false failure.
tarball_listing="$(tar -tzf "$tarball")"
for member in \
    "$bundle_name/VERSION" \
    "$bundle_name/manifest.json" \
    "$bundle_name/include/chronon3d/c_api/chronon3d.h" \
    "$bundle_name/lib/cmake/Chronon3D/Chronon3DConfig.cmake"; do
    grep -Fxq "$member" <<< "$tarball_listing" \
        || fail "bundle tarball missing expected member: $member"
done

if [[ "$KEEP" != "1" ]]; then
    rm -rf "$bundle_dir"
    log "removed intermediate bundle dir (set CHRONON3D_BUNDLE_KEEP=1 to keep)"
else
    log "kept bundle dir at $bundle_dir"
fi

log "bundle: $tarball ($(du -h "$tarball" | awk '{print $1}'))"
# Machine-readable outputs on stdout so downstream tooling (e.g. the
# relocation gate) can consume the exact platform-derived artifact path.
echo "BUNDLE_TARBALL=$tarball"
echo "CHRONON_SDK_BUNDLE_PASS"
exit 0
