# ============================================================================
# cmake/Chronon3DPublicHeaders.cmake
#
# Single source of truth for the V0.1 SDK public-header manifest.
# NO GLOB. Every header is enumerated explicitly.
# ============================================================================

set(CHRONON3D_PUBLIC_HEADERS
    # ── Umbrella ────────────────────────────────────────────────────────
    "${CMAKE_SOURCE_DIR}/include/chronon3d/chronon3d.hpp"

    # ── canonical sdk::* surface (V0.1 MVP) ──────────────────────────────
    "${CMAKE_SOURCE_DIR}/include/chronon3d/sdk/render_engine.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/sdk/render_output.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/sdk/render_error.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/sdk/render_request.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/sdk/render_settings.hpp"

    # ── Composition type ─────────────────────────────────────────────────
    "${CMAKE_SOURCE_DIR}/include/chronon3d/timeline/composition.hpp"
    # ── Transitive closure ───────────────────────────────────────────────
    "${CMAKE_SOURCE_DIR}/include/chronon3d/animation/core/animated_value.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/animation/core/animation_track.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/animation/core/detail/animated_value_bezier.inl"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/animation/core/detail/animated_value_evaluation.inl"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/animation/core/detail/animated_value_expressions.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/animation/core/detail/animated_value_roving.inl"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/animation/core/keyframe.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/animation/core/quaternion_track.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/animation/easing/easing.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/animation/easing/interpolate.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/animation/motion/timeline.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/animation/effects/animated_transform.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/animation/effects/stagger.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/api/render_engine.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/assets/asset_metadata.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/assets/asset_registry.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/backends/image/image_writer.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/backends/software/render_settings.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/backends/software/sampling/edge_mode.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/backends/video/video_source.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/cache/cache_diagnostics.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/cache/cache_policy.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/cache/framebuffer_pool.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/cache/lru_cache.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/cache/node_cache.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/compositor/alpha.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/compositor/blend_mode.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/compositor/composite_operator.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/core/composition/composition_registry.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/core/config.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/core/dirty_fallback_reason.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/core/enum_utils.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/core/memory/arena.hpp"
    # detail/ framebuffer_impl.hpp transitively required by core/memory/framebuffer.hpp:27
    # (relative `#include "detail/framebuffer_impl.hpp"`); de-facto public by
    # directory convention (under include/chronon3d/, NOT under internal/).
    "${CMAKE_SOURCE_DIR}/include/chronon3d/core/memory/detail/framebuffer_impl.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/core/memory/framebuffer.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/core/memory/framebuffer_handle.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/core/memory/framebuffer_slot_view.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/core/memory/memory_utils.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/core/profiling/counters.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/core/profiling/profiling.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/core/profiling/trace_categories.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/core/scheduler/scheduler_mode.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/core/types/frame.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/core/types/frame_context.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/core/types/result.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/core/types/sample_time.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/core/types/time.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/core/types/types.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/effects/effect_catalog_data.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/effects/effect_catalog.def"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/effects/effect_category.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/effects/effect_descriptor.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/effects/effect_execution_context.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/effects/effect_ids.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/effects/effect_instance.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/effects/effect_params.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/effects/effect_stage.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/effects/effect_traits.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/effects/effect_type.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/effects/presets/glow_presets.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/geometry/bounds.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/geometry/mesh.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/geometry/vertex.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/graphics/gradient.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/graphics/shape_style/fill_style.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/graphics/shape_style/stroke_style.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/layout/layout_flow_grid.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/layout/layout_rules.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/math/camera_2_5d_projection.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/math/camera_pose.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/math/camera_projection_contract.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/math/camera_projection_resolver.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/math/color.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/math/expression.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/math/expression_types.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/math/glm_types.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/math/near_plane_clip.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/math/projection_context.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/math/projector_2_5d.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/math/raster_utils.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/math/renderer_state.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/math/transform.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/presets/motion_animation.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/presets/motion_object.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/presets/motion_state.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/registry/shape_ids.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/registry/shape_params.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/registry/shape_registry.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/media/media_placement.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/render_graph/cache/scene_program_cache.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/internal/render_graph/cache/scene_program_store.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/render_graph/compiler/compiled_frame_graph.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/render_graph/compiler/compiled_scene_program.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/render_graph/core/cache_policy.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/render_graph/core/node_identity.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/render_graph/core/render_graph_hashing.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/internal/render_graph/core/scene_hasher.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/render_graph/nodes/render_graph_node.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/render_graph/render_backend.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/render_graph/render_graph.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/render_graph/render_graph_context.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/rendering/depth_grade.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/rendering/light_context.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/rendering/lighting_rig.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/rendering/projected_card.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/rendering/shadow_settings.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/runtime/dirty_history.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/runtime/frame_history.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/internal/runtime/render_session.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/internal/runtime/session_services.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/runtime/telemetry/render_telemetry_record.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/builders/builder_params.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/builders/scene_builder.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/builders/layer_builder.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/builders/detail/layer_builder_text.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/builders/detail/layer_builder_inline.inl"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/builders/detail/scene_builder_inline.inl"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/builders/detail/scene_builder_layers.inl"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/builders/detail/scene_builder_sequences.inl"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/builders/detail/scene_builder_camera.inl"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/builders/camera_api.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/builders/null_builder.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/builders/text_run_builder.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/camera/camera_v1/arc_length_table.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/camera/camera_v1/camera_catalog.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/camera/camera_v1/camera_constraint.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/camera/camera_v1/camera_descriptor.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/camera/camera_v1/camera_descriptor_adapters.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/camera/camera_v1/camera_descriptor_fingerprint.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/camera/camera_v1/camera_framing_solver.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/camera/camera_v1/camera_motion_blur.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/camera/camera_v1/camera_motion_context.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/camera/camera_v1/camera_program.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/camera/camera_v1/camera_program_compiler.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/camera/camera_v1/camera_session.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/camera/camera_v1/camera_session_cache.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/camera/camera_v1/camera_trajectory.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/camera/camera_v1/evaluated_projection.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/camera/camera_v1/register_camera_v1.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/camera/camera_v1/shot_timeline.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/camera/animated_camera_2_5d.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/camera/camera_rig_builder.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/camera/camera.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/camera/camera_2_5d.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/camera/camera_common_types.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/camera/camera_projection_source.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/camera/dof.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/camera/lens_model.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/camera/camera_rig.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/core/depth_role.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/core/card3d_material.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/core/hierarchy_resolver.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/core/effect_stack.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/core/mask_utils.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/core/scene.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/core/transition.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/layer/layer.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/layer/layer_hierarchy.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/layer/mask.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/layer/track_matte.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/render/render_node.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/render/render_runtime.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/render/resolved_types.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/shape/fill.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/shape/material_2_5d.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/shape/path.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/shape/shape.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/scene/model/shape/transform_3d.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/simd/kernels.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/text/animated_text_document.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/text/animation/glyph_instance_state.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/text/animation/text_animator_evaluator.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/text/animation/text_animator_properties.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/text/animation/text_animator_spec.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/text/animation/text_animator_stack.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/text/text_document.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/text/text_layout_cache.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/text/text_layout_identity.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/text/font_engine.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/text/glyph_selector.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/text/paragraph_style.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/text/text_animator_property.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/text/text_direction.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/text/text_material.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/text/text_run.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/text/text_run_layout.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/text/text_run_hash.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/text/text_run_shape.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/vector/path_factories.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/vector/shape_style.hpp"
    "${CMAKE_SOURCE_DIR}/include/chronon3d/timeline/composition_props.hpp"
    # ── Timeline V2 single-source-of-truth (M1.7 Step 1, TICKET-SEQUENCE-LOCAL-FRAME) ──
    #   TimeRange + SequenceNode + TimelineSampleContext + TimelineResolver
    #   in namespace `chronon3d::timeline::v2`. Designed green: zero code-side
    #   mutate, zero new singleton, ABI pubblico invariato. Step 2 wireà i
    #   legacy adapters; Step 3 abiliterà `SequenceBuilder`; Step 4 eliminerà
    #   `Layer.from/duration` e `SequenceContext` legacy.
    "${CMAKE_SOURCE_DIR}/include/chronon3d/timeline/timeline_resolver_v2.hpp"
    # ── M1.7 Step 2: Legacy Adapters (Layer → SequenceNode + FrameContext → TimelineSampleContext) ──
    #   `is_active(TimeRange, Frame)` constexpr + `make_sequence_from_layer(Layer)` +
    #   `make_sample_context(FrameContext)`. Pure additive: AGENTS Cat-3 freeze-compliant
    #   (zero nuovi singleton / zero modifiche al codice esistente / zero ABI bloat).
    #   Destinato all'eliminazione a Step 4 (TICKET-SEQUENCE-LOCAL-FRAME).
    "${CMAKE_SOURCE_DIR}/include/chronon3d/timeline/legacy_adapters.hpp"
    # ── M1.7 Step 1: Asset Readiness V2 single-source-of-truth (TICKET-ASSET-READINESS) ──
    #   AssetKind enum + AssetRef POD + AssetManifest class + AssetPreflightResult POD +
    #   AssetPreflightResolver class in namespace `chronon3d::assets::v2` (distinto da
    #   `chronon3d::AssetType` esistente in asset_metadata.hpp). Designed green: zero
    #   code-side mutate, zero new singleton, ABI pubblico preservato. Step 2 wireà i
    #   legacy adapters (font_path/image_path/video_path/audio_path → AssetRef);
    #   Step 3 popolerà check_* reali + RenderJob::start() preflight; Step 4 eliminerà
    #   TextPreflight/ImagePreflight/VideoPreflight/AudioPreflight/FontPreflight e i
    #   fallback silenziosi.
    "${CMAKE_SOURCE_DIR}/include/chronon3d/assets/asset_readiness_v2.hpp"
    # ── M1.7 Step 2: Asset Legacy Adapters (path raw → AssetRef + manifest + render-error bridge) ──
    #   `make_asset_ref(kind, path, owner, required)` POD builder + `register_path(manifest, ...)`
    #   convenience wrapper + `accumulate_preflight_result(result, ref, found)` bridge accumulator.
    #   Pure additive: AGENTS Cat-3 freeze-compliant (zero nuovi singleton / zero modifiche al codice
    #   esistente / zero ABI bloat / FNV-1a cache key invariato). Destinato all'eliminazione a Step 4.
    "${CMAKE_SOURCE_DIR}/include/chronon3d/assets/legacy_adapters.hpp"
)
