# ==============================================================================
# cmake/Chronon3DSdkTargets.cmake — SDK consumer-facing targets
# ==============================================================================

add_library(chronon3d_sdk_impl STATIC)

chronon3d_link_registered_objects_into_archive(chronon3d_sdk_impl)

include(${CMAKE_SOURCE_DIR}/cmake/Chronon3DSdkArchive.cmake)
set_target_properties(chronon3d_sdk_impl PROPERTIES EXPORT_NAME SDKImpl)

add_library(chronon3d_sdk INTERFACE)
target_include_directories(chronon3d_sdk INTERFACE
    $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/include>
    $<INSTALL_INTERFACE:include>
)
target_link_libraries(chronon3d_sdk INTERFACE
    $<BUILD_INTERFACE:chronon3d_pipeline>
    $<INSTALL_INTERFACE:chronon3d_sdk_impl>
)

foreach(_entry IN LISTS CHRONON3D_SDK_PUBLIC_DEPS)
    string(REPLACE "|" ";" _pair "${_entry}")
    list(GET _pair 0 _target_alias)
    target_link_libraries(chronon3d_sdk INTERFACE
        $<INSTALL_INTERFACE:${_target_alias}>
    )
endforeach()

set_target_properties(chronon3d_sdk PROPERTIES EXPORT_NAME SDK)
add_library(Chronon3D::SDK ALIAS chronon3d_sdk)

if(CHRONON3D_BUILD_C_API)
    # src/c_api/chronon3d_version.hpp is GENERATED by the configure_file  # drift-class: false-positive (generated at build time)
    # below into ${CMAKE_CURRENT_BINARY_DIR}/chronon3d_version.hpp — it is
    # intentionally absent from the source tree (generated header, not drift).
    configure_file(
        ${CMAKE_SOURCE_DIR}/src/c_api/chronon3d_version.hpp.in
        ${CMAKE_CURRENT_BINARY_DIR}/chronon3d_version.hpp
        @ONLY
    )
    add_library(chronon3d_c SHARED
        ${CMAKE_SOURCE_DIR}/src/c_api/chronon3d_c_api.cpp
    )
    target_include_directories(chronon3d_c
        PUBLIC
            $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/include>
            $<INSTALL_INTERFACE:include>
        PRIVATE
            ${CMAKE_CURRENT_BINARY_DIR}
    )
    target_link_libraries(chronon3d_c PRIVATE
        chronon3d_sdk
        nlohmann_json::nlohmann_json
        # TICKET-JSON-SCHEMA-VALIDATOR — chronon3d_render_plan is the
        # render-plan JSON Schema validator OBJECT library.  It is also
        # aggregated into libchronon3d_sdk_impl.a via
        # CHRONON3D_REGISTRY_OBJECT_LIBS, which is what the C++ SDK facade
        # (sdk::RenderEngine::compile_plan_json/render_plan_file) relies
        # on.  We still link it directly to the C API SHARED lib here so
        # chronon3d_c resolves the decode/compile symbols for its own
        # standalone linkage.  In-tree tests link chronon3d_render_plan
        # directly via tests/c_abi_tests.cmake LINK_TARGETS.
        chronon3d_render_plan
        chronon3d_render_plan_compiler
    )
    # Windows export contract: define CHRONON3D_BUILD_DLL only while building
    # the shared library so chronon3d.h expands CHRONON3D_API to
    # __declspec(dllexport); consumers see __declspec(dllimport).  No-op on
    # ELF platforms (the visibility-attribute path is taken instead).
    target_compile_definitions(chronon3d_c PRIVATE CHRONON3D_BUILD_DLL)
    # VERSION/SOVERSION give the shared library a real SONAME
    # (libchronon3d_c.so.2) so Linux can distinguish ABI-incompatible
    # releases.  SOVERSION tracks the C ABI contract reported by
    # chronon_abi_version() (currently 2), NOT the project version; a
    # breaking ABI change must bump BOTH together.
    set_target_properties(chronon3d_c PROPERTIES
        EXPORT_NAME C
        VERSION ${PROJECT_VERSION}
        SOVERSION 2
        CXX_VISIBILITY_PRESET hidden
        VISIBILITY_INLINES_HIDDEN ON
        INSTALL_RPATH "$ORIGIN"
    )
    add_library(Chronon3D::C ALIAS chronon3d_c)
endif()
