#include <chronon3d/backends/assets/image_renderer.hpp>
#include <chronon3d/compositor/blend_mode.hpp>
#include <chronon3d/math/raster_utils.hpp>
#include <chronon3d/scene/model/core/mask_utils.hpp>
#include <chronon3d/media/media_placement.hpp>
#include <chronon3d/core/telemetry/render_telemetry.hpp>
#include <chronon3d/core/profiling/counters.hpp>
#include <chronon3d/core/profiling/profiling.hpp>
#include "../software/utils/blend2d_bridge.hpp"
#include <tbb/blocked_range.h>
#include <tbb/parallel_for.h>
#include <spdlog/spdlog.h>
#include <algorithm>
#include <cmath>
#include <cstring>
#include <sstream>

#include "image_renderer_support_detail.hpp"
#include "image_renderer_draw_detail.hpp"
